<?php
declare(strict_types=1);

namespace ImWiki\Bootstrap;

use ImWiki\Http\Response;
use ImWiki\Http\Router;
use ImWiki\Support\Url;

final class RouteRegistrar
{
    /** @param array<string,object> $controllers */
    public static function register(Router $router,array $controllers):void
    {
        $auth=$controllers['auth'];$wiki=$controllers['wiki'];$admin=$controllers['admin'];$adminOperations=$controllers['adminOperations'];$api=$controllers['api'];$notifications=$controllers['notifications'];$tasks=$controllers['tasks'];$access=$controllers['access'];$attachments=$controllers['attachments'];$diff=$controllers['diff'];$apiTokens=$controllers['apiTokens'];$restApi=$controllers['restApi'];$workflow=$controllers['workflow'];$properties=$controllers['properties'];$search=$controllers['search'];$suggestions=$controllers['suggestions'];$publicShares=$controllers['publicShares'];$security=$controllers['security'];$sessions=$controllers['sessions'];$mail=$controllers['mail'];$passwordReset=$controllers['passwordReset'];$interactions=$controllers['interactions'];$webhooks=$controllers['webhooks'];$userAdmin=$controllers['userAdmin'];$profile=$controllers['profile'];$presence=$controllers['presence'];$contentAdmin=$controllers['contentAdmin'];$securityDashboard=$controllers['securityDashboard'];$pageOperations=$controllers['pageOperations'];$templates=$controllers['templates'];$spaceAdmin=$controllers['spaceAdmin'];$importExport=$controllers['importExport'];$backup=$controllers['backup'];$tree=$controllers['tree'];

        $router->get('/',fn()=>Response::redirect(Url::to(isset($_SESSION['user_id'])?'/dashboard':'/login')));

        $router->get('/login',[$auth,'loginForm']);$router->post('/login',[$auth,'login']);$router->get('/forgot-password',[$passwordReset,'requestForm']);$router->post('/forgot-password',[$passwordReset,'requestReset']);$router->get('/password-reset',[$passwordReset,'resetForm']);$router->post('/password-reset',[$passwordReset,'reset']);$router->get('/login/2fa',[$auth,'twoFactorForm']);$router->post('/login/2fa',[$auth,'twoFactorVerify']);$router->post('/logout',[$auth,'logout']);

        $router->get('/dashboard',[$wiki,'dashboard']);$router->get('/profile/dashboard',[$wiki,'dashboardSettings']);$router->post('/profile/dashboard',[$wiki,'saveDashboardSettings']);$router->get('/recent',[$wiki,'recentViewed']);$router->post('/recent/clear',[$wiki,'clearRecent']);$router->get('/drafts',[$wiki,'drafts']);$router->post('/drafts/{id}/delete',[$wiki,'deleteDraft']);

        $router->get('/spaces',[$wiki,'spaces']);$router->post('/spaces',[$wiki,'createSpace']);$router->get('/spaces/{key}',[$wiki,'space']);$router->get('/spaces/{key}/export.zip',[$importExport,'spaceZip']);$router->post('/spaces/{key}/import',[$importExport,'import']);$router->get('/spaces/{key}/settings',[$spaceAdmin,'settings']);$router->post('/spaces/{key}/settings',[$spaceAdmin,'save']);$router->post('/spaces/{key}/archive',[$spaceAdmin,'archive']);$router->get('/spaces/{key}/webhooks',[$webhooks,'index']);$router->post('/spaces/{key}/webhooks',[$webhooks,'create']);$router->post('/spaces/{key}/webhooks/{id}/revoke',[$webhooks,'revoke']);$router->post('/spaces/{key}/watch',[$wiki,'watchSpace']);$router->post('/spaces/{key}/favorite',[$wiki,'favoriteSpace']);
        $router->get('/spaces/{key}/pages/create',[$wiki,'newPage']);$router->post('/spaces/{key}/pages/create',[$wiki,'createPage']);$router->get('/spaces/{key}/pages/{slug}',[$wiki,'friendlyPage']);

        $router->get('/pages/{id}',[$wiki,'page']);$router->get('/pages/{id}/edit',[$wiki,'editPage']);$router->post('/pages/{id}/edit',[$wiki,'updatePage']);$router->get('/pages/{id}/export.md',[$importExport,'pageMarkdown']);$router->get('/pages/{id}/export.html',[$importExport,'pageHtml']);$router->get('/pages/{id}/history',[$wiki,'history']);$router->get('/pages/{id}/move',[$pageOperations,'dialog']);$router->post('/pages/{id}/move',[$pageOperations,'move']);$router->post('/pages/{id}/copy',[$pageOperations,'copy']);$router->post('/pages/{id}/archive',[$pageOperations,'archive']);$router->post('/pages/{id}/trash',[$pageOperations,'trash']);$router->get('/pages/{id}/diff',[$diff,'compare']);$router->post('/pages/{id}/restore',[$wiki,'restore']);
        $router->post('/pages/{id}/comments',[$wiki,'comment']);$router->post('/pages/{id}/favorite',[$wiki,'favorite']);$router->post('/pages/{id}/watch',[$wiki,'watchPage']);$router->post('/pages/{id}/reactions',[$interactions,'pageReaction']);$router->post('/pages/{id}/comments/{commentId}/reactions',[$interactions,'commentReaction']);$router->post('/pages/{id}/comments/{commentId}/status',[$interactions,'threadStatus']);$router->post('/pages/{id}/inline-comments',[$interactions,'inlineCreate']);$router->post('/pages/{id}/inline-comments/{inlineId}/status',[$interactions,'inlineStatus']);$router->post('/pages/{id}/tasks',[$tasks,'create']);$router->post('/tasks/{id}/complete',[$tasks,'complete']);$router->get('/tasks',[$tasks,'mine']);
        $router->get('/pages/{id}/restrictions',[$access,'show']);$router->get('/pages/{id}/public-shares',[$publicShares,'manage']);$router->post('/pages/{id}/public-shares',[$publicShares,'create']);$router->post('/pages/{id}/public-shares/{shareId}/revoke',[$publicShares,'revoke']);$router->post('/pages/{id}/restrictions/mode',[$access,'setMode']);$router->post('/pages/{id}/restrictions/grants',[$access,'grant']);$router->post('/pages/{id}/restrictions/grants/{grantId}/revoke',[$access,'revoke']);$router->post('/pages/{id}/attachments',[$attachments,'upload']);$router->get('/attachments/{id}/download',[$attachments,'download']);$router->get('/attachments/{id}/preview',[$attachments,'preview']);$router->get('/attachments/{id}/versions',[$attachments,'versions']);$router->get('/attachment-versions/{versionId}/download',[$attachments,'downloadVersion']);

        $router->post('/api/pages/{id}/draft',[$api,'autosave']);$router->post('/api/pages/{id}/presence',[$presence,'heartbeat']);$router->post('/api/pages/{id}/tree-move',[$pageOperations,'treeMove']);$router->get('/api/spaces/{key}/tree',[$tree,'children']);$router->get('/api/users/autocomplete',[$api,'users']);$router->get('/api/search/suggestions',[$suggestions,'search']);

        $router->get('/notifications',[$notifications,'index']);$router->get('/profile/notifications',[$notifications,'preferences']);$router->post('/profile/notifications',[$notifications,'savePreferences']);$router->post('/notifications/{id}/read',[$notifications,'markRead']);$router->post('/notifications/read-all',[$notifications,'markAllRead']);
        $router->get('/profile',[$profile,'index']);$router->post('/profile',[$profile,'update']);$router->post('/profile/password',[$profile,'password']);$router->get('/profile/security',[$security,'index']);$router->get('/profile/sessions',[$sessions,'index']);$router->post('/profile/sessions/revoke-others',[$sessions,'revokeOthers']);$router->post('/profile/sessions/{id}/revoke',[$sessions,'revoke']);$router->post('/profile/security/2fa/begin',[$security,'begin2fa']);$router->post('/profile/security/2fa/confirm',[$security,'confirm2fa']);$router->post('/profile/security/2fa/disable',[$security,'disable2fa']);
        $router->get('/api-tokens',[$apiTokens,'index']);$router->post('/api-tokens',[$apiTokens,'create']);$router->post('/api-tokens/{id}/revoke',[$apiTokens,'revoke']);

        $router->post('/pages/{id}/properties',[$properties,'set']);$router->post('/pages/{id}/properties/{propertyId}/remove',[$properties,'remove']);$router->post('/pages/{id}/workflow/request',[$workflow,'request']);$router->post('/pages/{id}/workflow/decision',[$workflow,'decide']);$router->post('/pages/{id}/workflow/publish',[$workflow,'publish']);$router->post('/pages/{id}/workflow/draft',[$workflow,'draft']);$router->post('/admin/workflow',[$workflow,'setting']);

        $router->get('/api/v1/spaces',[$restApi,'spaces']);$router->get('/api/v1/pages/{id}',[$restApi,'page']);$router->post('/api/v1/pages',[$restApi,'createPage']);$router->put('/api/v1/pages/{id}',[$restApi,'updatePage']);$router->get('/api/v1/search',[$restApi,'search']);$router->post('/api/v1/pages/{id}/attachments',[$restApi,'uploadAttachment']);$router->get('/api/v1/attachments/{id}',[$restApi,'downloadAttachment']);

        $router->get('/share/{token}',[$publicShares,'view']);$router->post('/share/{token}',[$publicShares,'view']);$router->get('/search',[$search,'index']);$router->post('/search/save',[$search,'save']);$router->post('/saved-searches/{id}/remove',[$search,'remove']);

        $router->get('/admin/logs',[$adminOperations,'logs']);$router->get('/admin/retention',[$adminOperations,'retention']);$router->post('/admin/retention',[$adminOperations,'saveRetention']);$router->post('/admin/retention/cleanup',[$adminOperations,'cleanup']);$router->get('/admin/database',[$adminOperations,'database']);$router->post('/admin/cache/clear',[$adminOperations,'clearCache']);
        $router->get('/admin/users',[$userAdmin,'users']);$router->get('/admin/users/create',[$userAdmin,'createForm']);$router->post('/admin/users/create',[$userAdmin,'create']);$router->get('/admin/users/{id}/edit',[$userAdmin,'editForm']);$router->post('/admin/users/{id}/edit',[$userAdmin,'update']);$router->post('/admin/users/{id}/password',[$userAdmin,'resetPassword']);$router->post('/admin/users/{id}/delete',[$userAdmin,'delete']);$router->get('/admin/groups',[$userAdmin,'groups']);$router->post('/admin/groups',[$userAdmin,'createGroup']);$router->get('/admin/groups/{id}',[$userAdmin,'group']);$router->post('/admin/groups/{id}',[$userAdmin,'updateGroup']);$router->post('/admin/groups/{id}/delete',[$userAdmin,'deleteGroup']);$router->post('/admin/groups/{id}/members',[$userAdmin,'addMember']);$router->post('/admin/groups/{id}/members/{userId}/remove',[$userAdmin,'removeMember']);
        $router->get('/admin/system',[$admin,'system']);$router->get('/admin/backup',[$backup,'index']);$router->post('/admin/backup/create',[$backup,'create']);$router->get('/admin/content',[$contentAdmin,'index']);$router->get('/admin/templates',[$templates,'index']);$router->post('/admin/templates',[$templates,'create']);$router->get('/admin/templates/{id}',[$templates,'edit']);$router->post('/admin/templates/{id}',[$templates,'update']);$router->post('/admin/templates/{id}/clone',[$templates,'clone']);$router->post('/admin/templates/{id}/archive',[$templates,'archive']);$router->get('/admin/security',[$securityDashboard,'index']);$router->get('/admin/trash',[$pageOperations,'trashList']);$router->post('/admin/trash/{id}/restore',[$pageOperations,'restore']);$router->post('/admin/trash/{id}/purge',[$pageOperations,'purge']);$router->post('/admin/maintenance',[$admin,'maintenance']);$router->get('/admin/mail',[$mail,'index']);$router->post('/admin/mail',[$mail,'save']);$router->post('/admin/mail/test',[$mail,'test']);$router->post('/admin/public-sharing',[$publicShares,'adminSetting']);
    }
}
