<?php
declare(strict_types=1);

namespace ImWiki\Services;

use ImWiki\Exceptions\AuthorizationException;
use ImWiki\Exceptions\StorageException;
use ImWiki\Exceptions\ValidationException;
use ImWiki\Repositories\PageRepository;
use ImWiki\Security\Authorization;
use ImWiki\Storage\FileScannerInterface;
use ImWiki\Storage\NoopFileScanner;
use ImWiki\Storage\StorageManager;
use PDO;

final class AttachmentService
{
    private const BLOCKED_EXTENSIONS=['php','php3','php4','php5','php7','php8','phtml','phar','cgi','pl','py','sh','bash','exe','com','bat','cmd','msi','svg','htaccess','user.ini'];
    private const BLOCKED_MIME=['application/x-httpd-php','application/x-php','text/x-php','application/x-sh','application/x-executable','application/x-msdownload','image/svg+xml'];
    private FileScannerInterface $scanner;private StorageManager $storage;
    public function __construct(private readonly PDO $pdo,private readonly string $prefix,private readonly PageRepository $pages,private readonly Authorization $authz,private readonly string $root,?FileScannerInterface $scanner=null,?StorageManager $storage=null){$this->scanner=$scanner??new NoopFileScanner();$this->storage=$storage??new StorageManager($pdo,$prefix,$root);}

    public function storeUploaded(int $pageId,array $file,int $userId):int
    {
        $page=$this->pages->find($pageId);if(!$page||!$this->authz->canAttachPage($userId,$page))throw new AuthorizationException();$size=(int)($file['size']??0);if((int)($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK||$size<=0)throw new ValidationException('Nieprawidłowy plik.');$this->storage->assertUploadAllowed($userId,(int)$page['space_id'],$size);$tmp=(string)($file['tmp_name']??'');if($tmp===''||!is_uploaded_file($tmp))throw new ValidationException('Nieprawidłowy plik tymczasowy.');$original=mb_substr(basename((string)($file['name']??'plik')),0,255);if($original===''||str_contains($original,"\0"))throw new ValidationException('Nieprawidłowa nazwa pliku.');$ext=mb_strtolower(pathinfo($original,PATHINFO_EXTENSION));if($ext!==''&&in_array($ext,self::BLOCKED_EXTENSIONS,true))throw new ValidationException('Ten typ pliku jest zablokowany.');$mime=(new \finfo(FILEINFO_MIME_TYPE))->file($tmp)?:'application/octet-stream';if(in_array(mb_strtolower($mime),self::BLOCKED_MIME,true))throw new ValidationException('Ten typ pliku jest zablokowany.');$checksum=hash_file('sha256',$tmp);if($checksum===false)throw new StorageException('Nie można obliczyć sumy kontrolnej pliku.');$scan=$this->scanner->scan($tmp,$original,$mime);$status=(string)($scan['status']??'error');if(!in_array($status,['clean','infected','error','not_scanned'],true))$status='error';$stored=bin2hex(random_bytes(24));$quarantined=$status==='infected';$dir=$quarantined?$this->root.'/storage/private/quarantine':$this->root.'/storage/uploads';if(!is_dir($dir)&&!@mkdir($dir,0770,true)&&!is_dir($dir))throw new StorageException('Nie można utworzyć katalogu plików.');$dest=$dir.'/'.$stored;if(!move_uploaded_file($tmp,$dest))throw new StorageException('Nie udało się zapisać pliku.');@chmod($dest,0640);
        try{$this->pdo->beginTransaction();$find=$this->pdo->prepare("SELECT * FROM `{$this->prefix}attachments` WHERE page_id=? AND original_name=? AND deleted_at IS NULL ORDER BY id LIMIT 1 FOR UPDATE");$find->execute([$pageId,$original]);$attachment=$find->fetch();if($attachment){$attachmentId=(int)$attachment['id'];$version=(int)$attachment['current_version']+1;$ver=$this->pdo->prepare("INSERT INTO `{$this->prefix}attachment_versions` (attachment_id,version_no,stored_name,mime_type,size_bytes,checksum_sha256,uploader_id,created_at) VALUES (?,?,?,?,?,?,?,UTC_TIMESTAMP())");$ver->execute([$attachmentId,$version,$stored,$mime,$size,$checksum,$userId]);$upd=$this->pdo->prepare("UPDATE `{$this->prefix}attachments` SET stored_name=?,mime_type=?,size_bytes=?,current_version=?,uploader_id=?,checksum_sha256=?,scan_status=?,quarantine_reason=?,created_at=UTC_TIMESTAMP() WHERE id=?");$upd->execute([$stored,$mime,$size,$version,$userId,$checksum,$status,$quarantined?mb_substr((string)($scan['reason']??'Scanner reported infected file.'),0,1000):null,$attachmentId]);}else{$ins=$this->pdo->prepare("INSERT INTO `{$this->prefix}attachments` (page_id,uploader_id,original_name,stored_name,mime_type,size_bytes,current_version,checksum_sha256,scan_status,quarantine_reason,created_at) VALUES (?,?,?,?,?,?,1,?,?,?,UTC_TIMESTAMP())");$ins->execute([$pageId,$userId,$original,$stored,$mime,$size,$checksum,$status,$quarantined?mb_substr((string)($scan['reason']??'Scanner reported infected file.'),0,1000):null]);$attachmentId=(int)$this->pdo->lastInsertId();$ver=$this->pdo->prepare("INSERT INTO `{$this->prefix}attachment_versions` (attachment_id,version_no,stored_name,mime_type,size_bytes,checksum_sha256,uploader_id,created_at) VALUES (?,1,?,?,?,?,?,UTC_TIMESTAMP())");$ver->execute([$attachmentId,$stored,$mime,$size,$checksum,$userId]);}$this->pdo->commit();if($quarantined)$this->audit($userId,'attachment.quarantined',$attachmentId,'File quarantined by '.$this->scanner->name());return$attachmentId;}catch(\Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();@unlink($dest);throw$e;}
    }

    public function currentForPage(int $pageId):array{$stmt=$this->pdo->prepare("SELECT a.*,v.checksum_sha256 version_checksum,CONCAT(u.first_name,' ',u.last_name) uploader_name FROM `{$this->prefix}attachments` a LEFT JOIN `{$this->prefix}attachment_versions` v ON v.attachment_id=a.id AND v.version_no=a.current_version LEFT JOIN `{$this->prefix}users` u ON u.id=a.uploader_id WHERE a.page_id=? AND a.deleted_at IS NULL ORDER BY a.created_at DESC");$stmt->execute([$pageId]);return$stmt->fetchAll();}
    public function versions(int $attachmentId,int $userId):array{$attachment=$this->findLogical($attachmentId);if(!$attachment)throw new \RuntimeException('NOT_FOUND');$page=$this->pages->find((int)$attachment['page_id']);if(!$page||!$this->authz->canViewPage($userId,$page))throw new \RuntimeException('NOT_FOUND');$stmt=$this->pdo->prepare("SELECT v.*,CONCAT(u.first_name,' ',u.last_name) uploader_name FROM `{$this->prefix}attachment_versions` v JOIN `{$this->prefix}users` u ON u.id=v.uploader_id WHERE v.attachment_id=? ORDER BY v.version_no DESC");$stmt->execute([$attachmentId]);return['attachment'=>$attachment,'versions'=>$stmt->fetchAll(),'page'=>$page];}
    public function resolveCurrent(int $attachmentId,int $userId):array{$attachment=$this->findLogical($attachmentId);if(!$attachment||$attachment['scan_status']==='infected')throw new \RuntimeException('NOT_FOUND');$page=$this->pages->find((int)$attachment['page_id']);if(!$page||!$this->authz->canViewPage($userId,$page))throw new \RuntimeException('NOT_FOUND');$stmt=$this->pdo->prepare("SELECT v.*,a.original_name,a.page_id,a.scan_status FROM `{$this->prefix}attachment_versions` v JOIN `{$this->prefix}attachments` a ON a.id=v.attachment_id WHERE a.id=? AND v.version_no=a.current_version AND a.deleted_at IS NULL AND a.scan_status<>'infected'");$stmt->execute([$attachmentId]);$row=$stmt->fetch();if(!$row)throw new \RuntimeException('NOT_FOUND');return$row;}
    public function resolveVersion(int $versionId,int $userId):array{$stmt=$this->pdo->prepare("SELECT v.*,a.original_name,a.page_id,a.scan_status FROM `{$this->prefix}attachment_versions` v JOIN `{$this->prefix}attachments` a ON a.id=v.attachment_id WHERE v.id=? AND a.deleted_at IS NULL AND a.scan_status<>'infected'");$stmt->execute([$versionId]);$row=$stmt->fetch();if(!$row)throw new \RuntimeException('NOT_FOUND');$page=$this->pages->find((int)$row['page_id']);if(!$page||!$this->authz->canViewPage($userId,$page))throw new \RuntimeException('NOT_FOUND');return$row;}
    public function duplicateInfo(string $checksum,int $userId):array{$s=$this->pdo->prepare("SELECT a.id,a.page_id,a.original_name,a.size_bytes FROM `{$this->prefix}attachments` a WHERE a.checksum_sha256=? AND a.deleted_at IS NULL AND a.scan_status<>'infected' ORDER BY a.id DESC LIMIT 50");$s->execute([$checksum]);$out=[];foreach($s->fetchAll() as $row){$p=$this->pages->find((int)$row['page_id']);if($p&&$this->authz->canViewPage($userId,$p))$out[]=$row;}return$out;}
    public function stream(array $version):never{$this->streamFile($version,false);}
    public function streamInlineImage(array $version):never{$mime=mb_strtolower((string)$version['mime_type']);if(!in_array($mime,['image/jpeg','image/png','image/gif','image/webp'],true)){http_response_code(404);exit;}$this->streamFile($version,true);}
    private function streamFile(array $version,bool $inline):never{if(($version['scan_status']??'')==='infected'){http_response_code(404);exit;}$stored=(string)$version['stored_name'];if(!preg_match('/^[a-f0-9]{48}$/',$stored)){http_response_code(404);exit;}$path=$this->root.'/storage/uploads/'.$stored;if(!is_file($path)){http_response_code(404);exit;}header('Content-Type: '.(string)$version['mime_type']);header('Content-Length: '.filesize($path));header('Content-Disposition: '.($inline?'inline':'attachment').'; filename*=UTF-8\'\''.rawurlencode((string)$version['original_name']));header('X-Content-Type-Options: nosniff');if($inline)header("Content-Security-Policy: default-src 'none'; img-src 'self'");readfile($path);exit;}
    private function findLogical(int $attachmentId):?array{$stmt=$this->pdo->prepare("SELECT * FROM `{$this->prefix}attachments` WHERE id=? AND deleted_at IS NULL");$stmt->execute([$attachmentId]);return$stmt->fetch()?:null;}
    private function audit(int $uid,string $action,int $id,string $description):void{$s=$this->pdo->prepare("INSERT INTO `{$this->prefix}audit_log` (user_id,action,category,severity,request_id,resource_type,resource_id,description,metadata_json,ip_address,user_agent,created_at) VALUES (?,?,'security','warning',?,'attachment',?,?,NULL,'system','attachment-service',UTC_TIMESTAMP())");$s->execute([$uid,$action,defined('IMWIKI_REQUEST_ID')?IMWIKI_REQUEST_ID:null,$id,$description]);}
}
