<?php
declare(strict_types=1);
namespace ImWiki\Services;
use PDO;use RuntimeException;use ZipArchive;
final class BackupService{
 public function __construct(private readonly PDO $pdo,private readonly string $prefix,private readonly string $root){}
 public function create():string{if(!class_exists(ZipArchive::class))throw new RuntimeException('ZIP_UNAVAILABLE');$dir=$this->root.'/storage/private';if(!is_dir($dir)&&!mkdir($dir,0770,true)&&!is_dir($dir))throw new RuntimeException('STORAGE');$zipPath=tempnam($dir,'backup-');$sqlPath=tempnam($dir,'db-');if($zipPath===false||$sqlPath===false)throw new RuntimeException('TEMP');try{$this->dumpSql($sqlPath);$zip=new ZipArchive();if($zip->open($zipPath,ZipArchive::OVERWRITE)!==true)throw new RuntimeException('ZIP');$zip->addFile($sqlPath,'database.sql');$uploadDir=$this->root.'/storage/uploads';if(is_dir($uploadDir)){foreach(new \DirectoryIterator($uploadDir) as $f){if($f->isFile()&&preg_match('/^[a-f0-9]{48}$/',$f->getFilename()))$zip->addFile($f->getPathname(),'uploads/'.$f->getFilename());}}$config=require $this->root.'/config/config.php';$meta=['created_at'=>gmdate('c'),'version'=>defined('IMWIKI_VERSION')?IMWIKI_VERSION:null,'app'=>['name'=>$config['app']['name']??'imWiki','url'=>$config['app']['url']??'','language'=>$config['app']['language']??'pl','timezone'=>$config['app']['timezone']??'UTC'],'db'=>['host'=>$config['db']['host']??'','port'=>$config['db']['port']??3306,'database'=>$config['db']['database']??'','prefix'=>$config['db']['prefix']??'']];$zip->addFromString('metadata.json',json_encode($meta,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));$zip->addFromString('RESTORE.txt',"Restore wymaga odtworzenia database.sql i katalogu uploads oraz ponownego ustawienia sekretów/config.php przez administratora. Automatyczny restore z poziomu WWW jest celowo wyłączony.\n");$zip->close();@unlink($sqlPath);return$zipPath;}catch(\Throwable $e){@unlink($sqlPath);@unlink($zipPath);throw$e;}}
 private function dumpSql(string $path):void{$fh=fopen($path,'wb');if(!$fh)throw new RuntimeException('SQL_TEMP');fwrite($fh,"SET NAMES utf8mb4;\nSET FOREIGN_KEY_CHECKS=0;\n");$tables=$this->pdo->query('SHOW TABLES')->fetchAll(PDO::FETCH_COLUMN);foreach($tables as $table){$table=(string)$table;if(!str_starts_with($table,$this->prefix))continue;$create=$this->pdo->query('SHOW CREATE TABLE `'.str_replace('`','``',$table).'`')->fetch(PDO::FETCH_NUM);if(!$create)continue;fwrite($fh,"DROP TABLE IF EXISTS `{$table}`;\n".$create[1].";\n");$stmt=$this->pdo->query('SELECT * FROM `'.str_replace('`','``',$table).'`');while($row=$stmt->fetch(PDO::FETCH_ASSOC)){$cols=array_map(static fn($c)=>'`'.str_replace('`','``',(string)$c).'`',array_keys($row));$vals=[];foreach($row as $v)$vals[]=$v===null?'NULL':$this->pdo->quote((string)$v);fwrite($fh,'INSERT INTO `'.$table.'` ('.implode(',',$cols).') VALUES ('.implode(',',$vals).");\n");}}fwrite($fh,"SET FOREIGN_KEY_CHECKS=1;\n");fclose($fh);}
}
