<?php
declare(strict_types=1);

namespace ImWiki\Services;

use ImWiki\Exceptions\AuthorizationException;
use ImWiki\Exceptions\ConflictException;
use ImWiki\Exceptions\ValidationException;
use ImWiki\Repositories\PageRepository;
use ImWiki\Security\Authorization;
use PDO;

final class ContentGovernanceService
{
    public function __construct(private readonly PDO $pdo,private readonly string $prefix,private readonly PageRepository $pages,private readonly Authorization $authz){}

    public function classifications():array{return$this->pdo->query("SELECT * FROM `{$this->prefix}classifications` ORDER BY sort_order,name")->fetchAll()?:[];}
    public function saveClassification(int $actorId,?int $id,string $key,string $name,int $sort,bool $public,bool $enabled):int
    {
        if(!$this->authz->can($actorId,'classification.manage'))throw new AuthorizationException();$key=mb_strtolower(trim($key));$name=trim($name);if(!preg_match('/^[a-z0-9_-]{2,50}$/',$key)||$name===''||mb_strlen($name)>100)throw new ValidationException('Invalid classification.');if($id){$this->pdo->prepare("UPDATE `{$this->prefix}classifications` SET classification_key=?,name=?,sort_order=?,is_public=?,enabled=?,updated_at=UTC_TIMESTAMP() WHERE id=?")->execute([$key,$name,$sort,$public?1:0,$enabled?1:0,$id]);return$id;}$this->pdo->prepare("INSERT INTO `{$this->prefix}classifications` (classification_key,name,sort_order,is_public,enabled,created_at,updated_at) VALUES (?,?,?,?,?,UTC_TIMESTAMP(),UTC_TIMESTAMP())")->execute([$key,$name,$sort,$public?1:0,$enabled?1:0]);return(int)$this->pdo->lastInsertId();
    }

    public function classify(int $pageId,int $classificationId,int $actorId):void
    {
        $page=$this->page($pageId);if(!$this->authz->canEditPage($actorId,$page)&&!$this->authz->can($actorId,'classification.manage'))throw new AuthorizationException();$c=$this->pdo->prepare("SELECT COUNT(*) FROM `{$this->prefix}classifications` WHERE id=? AND enabled=1");$c->execute([$classificationId]);if((int)$c->fetchColumn()!==1)throw new ValidationException('Unknown classification.');$this->pdo->prepare("UPDATE `{$this->prefix}pages` SET classification_id=?,updated_at=UTC_TIMESTAMP() WHERE id=?")->execute([$classificationId,$pageId]);
    }

    public function setLegalHold(int $pageId,bool $enabled,int $actorId):void
    {
        if(!$this->authz->canManageLegalHold($actorId))throw new AuthorizationException();$page=$this->page($pageId);$this->pdo->prepare("UPDATE `{$this->prefix}pages` SET legal_hold=?,legal_hold_by=?,legal_hold_at=?,updated_at=UTC_TIMESTAMP() WHERE id=?")->execute([$enabled?1:0,$enabled?$actorId:null,$enabled?gmdate('Y-m-d H:i:s'):null,$pageId]);$this->audit($actorId,$enabled?'legal_hold.applied':'legal_hold.removed','page',$pageId,$enabled?'Applied legal hold':'Removed legal hold','compliance','warning',['page_uuid'=>$page['uuid']??null]);
    }

    public function deprecate(int $pageId,string $reason,?int $replacementId,int $actorId):void
    {
        $page=$this->page($pageId);if(!$this->authz->canEditPage($actorId,$page)&&!$this->authz->can($actorId,'content.governance'))throw new AuthorizationException();$reason=trim($reason);if($reason===''||mb_strlen($reason)>1000)throw new ValidationException('Deprecation reason is required.');if($replacementId!==null){if($replacementId===$pageId)throw new ValidationException('Replacement page cannot be the same page.');$target=$this->pages->find($replacementId);if(!$target||!$this->authz->canViewPage($actorId,$target))throw new ValidationException('Replacement page is unavailable.');}
        $this->pdo->prepare("UPDATE `{$this->prefix}pages` SET status='deprecated',deprecated_reason=?,replaced_by_page_id=?,deprecated_at=UTC_TIMESTAMP(),updated_at=UTC_TIMESTAMP() WHERE id=?")->execute([$reason,$replacementId,$pageId]);
    }

    public function restorePublished(int $pageId,int $actorId):void{$page=$this->page($pageId);if(!$this->authz->canEditPage($actorId,$page)&&!$this->authz->can($actorId,'content.governance'))throw new AuthorizationException();$this->pdo->prepare("UPDATE `{$this->prefix}pages` SET status='published',deprecated_reason=NULL,replaced_by_page_id=NULL,deprecated_at=NULL,updated_at=UTC_TIMESTAMP() WHERE id=?")->execute([$pageId]);}

    public function review(int $pageId,int $actorId,string $note=''):array
    {
        $page=$this->page($pageId);if(!$this->authz->canEditPage($actorId,$page)&&!$this->authz->can($actorId,'content.governance'))throw new AuthorizationException();$days=(int)($page['review_interval_days']??0);$next=$days>0?gmdate('Y-m-d H:i:s',time()+$days*86400):null;$note=mb_substr(trim($note),0,1000);$this->pdo->beginTransaction();try{$this->pdo->prepare("UPDATE `{$this->prefix}pages` SET last_reviewed_at=UTC_TIMESTAMP(),last_reviewed_by=?,review_note=?,verified_at=UTC_TIMESTAMP(),verified_by=?,next_review_at=?,review_date=?,updated_at=updated_at WHERE id=?")->execute([$actorId,$note?:null,$actorId,$next,$next?substr($next,0,10):null,$pageId]);$this->pdo->prepare("INSERT INTO `{$this->prefix}page_review_history` (page_id,reviewer_id,note,reviewed_at,next_review_at) VALUES (?,?,?,UTC_TIMESTAMP(),?)")->execute([$pageId,$actorId,$note?:null,$next]);$this->pdo->commit();}catch(\Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw$e;}return['verified_at'=>gmdate('Y-m-d H:i:s'),'next_review_at'=>$next];
    }
    public function setReviewSchedule(int $pageId,int $days,int $actorId):void{$page=$this->page($pageId);if(!$this->authz->canManagePageRestrictions($actorId,$page)&&!$this->authz->can($actorId,'content.governance'))throw new AuthorizationException();if($days!==0&&($days<7||$days>3650))throw new ValidationException('Review interval must be 0 or between 7 and 3650 days.');$next=$days>0?gmdate('Y-m-d H:i:s',time()+$days*86400):null;$this->pdo->prepare("UPDATE `{$this->prefix}pages` SET review_interval_days=?,next_review_at=?,review_date=?,updated_at=UTC_TIMESTAMP() WHERE id=?")->execute([$days?:null,$next,$next?substr($next,0,10):null,$pageId]);}

    public function staleScore(array $page):array
    {
        $score=0;$reasons=[];$updated=strtotime((string)($page['updated_at']??''))?:time();$age=(int)floor((time()-$updated)/86400);if($age>365){$score+=45;$reasons[]='not modified for over a year';}elseif($age>180){$score+=30;$reasons[]='not modified for over 180 days';}elseif($age>90){$score+=15;$reasons[]='not modified for over 90 days';}$review=$page['next_review_at']??$page['review_date']??null;if($review&&strtotime((string)$review)<time()){$score+=30;$reasons[]='review overdue';}$owner=(int)($page['owner_id']??0);if($owner>0){$s=$this->pdo->prepare("SELECT status FROM `{$this->prefix}users` WHERE id=? AND deleted_at IS NULL");$s->execute([$owner]);if((string)($s->fetchColumn()?:'disabled')!=='active'){$score+=25;$reasons[]='owner inactive';}}else{$score+=25;$reasons[]='owner missing';}$broken=$this->brokenInternalLinks((int)$page['id']);if($broken>0){$score+=min(20,$broken*5);$reasons[]=$broken.' broken internal links';}return['score'=>min(100,$score),'reasons'=>$reasons];
    }

    public function ownershipReport(int $actorId):array
    {
        if(!$this->authz->can($actorId,'content.governance'))throw new AuthorizationException();$pages=$this->pdo->query("SELECT p.id,p.uuid,p.title,p.owner_id,s.space_key,u.username owner_username,u.status owner_status FROM `{$this->prefix}pages` p JOIN `{$this->prefix}spaces` s ON s.id=p.space_id LEFT JOIN `{$this->prefix}users` u ON u.id=p.owner_id AND u.deleted_at IS NULL WHERE p.deleted_at IS NULL AND (p.owner_id IS NULL OR u.id IS NULL OR u.status<>'active') ORDER BY s.space_key,p.title LIMIT 1000")->fetchAll();$spaces=$this->pdo->query("SELECT s.id,s.name,s.space_key,s.owner_id,u.username owner_username,u.status owner_status FROM `{$this->prefix}spaces` s LEFT JOIN `{$this->prefix}users` u ON u.id=s.owner_id AND u.deleted_at IS NULL WHERE s.deleted_at IS NULL AND (u.id IS NULL OR u.status<>'active') ORDER BY s.name LIMIT 500")->fetchAll();return['pages'=>$pages?:[],'spaces'=>$spaces?:[]];
    }

    public function transferOwnership(array $pageIds,int $newOwnerId,int $actorId):array
    {
        if(!$this->authz->can($actorId,'content.governance'))throw new AuthorizationException();$u=$this->pdo->prepare("SELECT COUNT(*) FROM `{$this->prefix}users` WHERE id=? AND status='active' AND deleted_at IS NULL");$u->execute([$newOwnerId]);if((int)$u->fetchColumn()!==1)throw new ValidationException('New owner must be active.');$result=['success'=>[],'failed'=>[]];foreach($this->ids($pageIds,1000) as $id){try{$page=$this->page($id);if(!$this->authz->canManagePageRestrictions($actorId,$page)&&!$this->authz->can($actorId,'content.governance'))throw new AuthorizationException();$this->pdo->prepare("UPDATE `{$this->prefix}pages` SET owner_id=?,updated_at=UTC_TIMESTAMP() WHERE id=?")->execute([$newOwnerId,$id]);$result['success'][]=$id;}catch(\Throwable $e){$result['failed'][]=['id'=>$id,'reason'=>$this->publicReason($e)];}}return$result;
    }

    public function bulk(array $pageIds,string $action,array $payload,int $actorId):array
    {
        if(!$this->authz->can($actorId,'content.bulk')&&!$this->authz->isAdmin($actorId))throw new AuthorizationException();$result=['success'=>[],'failed'=>[]];foreach($this->ids($pageIds,500) as $id){try{$page=$this->page($id);match($action){'archive'=>$this->bulkStatus($page,'archived',$actorId),'publish'=>$this->bulkStatus($page,'published',$actorId),'deprecated'=>$this->bulkStatus($page,'deprecated',$actorId),'owner'=>$this->bulkOwner($page,(int)($payload['owner_id']??0),$actorId),'add_label'=>$this->addLabel($page,trim((string)($payload['label']??'')),$actorId),'remove_label'=>$this->removeLabel($page,trim((string)($payload['label']??'')),$actorId),'classification'=>$this->classify($id,(int)($payload['classification_id']??0),$actorId),'delete'=>$this->bulkDelete($page,$actorId),default=>throw new ValidationException('Unsupported bulk action.')};$result['success'][]=$id;}catch(\Throwable $e){$result['failed'][]=['id'=>$id,'reason'=>$this->publicReason($e)];}}return$result;
    }

    public function labels():array{return$this->pdo->query("SELECT l.id,l.name,COUNT(pl.page_id) usage_count FROM `{$this->prefix}labels` l LEFT JOIN `{$this->prefix}page_labels` pl ON pl.label_id=l.id GROUP BY l.id ORDER BY l.name")->fetchAll()?:[];}
    public function renameLabel(int $id,string $name,int $actorId):void{if(!$this->authz->can($actorId,'content.governance'))throw new AuthorizationException();$name=$this->labelName($name);$existing=$this->pdo->prepare("SELECT id FROM `{$this->prefix}labels` WHERE name=? AND id<>? LIMIT 1");$existing->execute([$name,$id]);$target=(int)($existing->fetchColumn()?:0);if($target>0){$this->mergeLabel($id,$target,$actorId);return;}$this->pdo->prepare("UPDATE `{$this->prefix}labels` SET name=? WHERE id=?")->execute([$name,$id]);}
    public function mergeLabel(int $sourceId,int $targetId,int $actorId):void{if(!$this->authz->can($actorId,'content.governance'))throw new AuthorizationException();if($sourceId===$targetId)return;$this->pdo->beginTransaction();try{$this->pdo->prepare("INSERT IGNORE INTO `{$this->prefix}page_labels` (page_id,label_id) SELECT page_id,? FROM `{$this->prefix}page_labels` WHERE label_id=?")->execute([$targetId,$sourceId]);$this->pdo->prepare("DELETE FROM `{$this->prefix}page_labels` WHERE label_id=?")->execute([$sourceId]);$this->pdo->prepare("DELETE FROM `{$this->prefix}labels` WHERE id=?")->execute([$sourceId]);$this->pdo->commit();}catch(\Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw$e;}}
    public function deleteLabel(int $id,int $actorId):void{if(!$this->authz->can($actorId,'content.governance'))throw new AuthorizationException();$this->pdo->beginTransaction();try{$this->pdo->prepare("DELETE FROM `{$this->prefix}page_labels` WHERE label_id=?")->execute([$id]);$this->pdo->prepare("DELETE FROM `{$this->prefix}labels` WHERE id=?")->execute([$id]);$this->pdo->commit();}catch(\Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw$e;}}

    public function relations(int $pageId,int $userId):array
    {
        $page=$this->page($pageId);if(!$this->authz->canViewPage($userId,$page))throw new AuthorizationException();$s=$this->pdo->prepare("SELECT r.id,r.relation_type,r.source_page_id,r.target_page_id,sp.title source_title,tp.title target_title FROM `{$this->prefix}page_relations` r JOIN `{$this->prefix}pages` sp ON sp.id=r.source_page_id JOIN `{$this->prefix}pages` tp ON tp.id=r.target_page_id WHERE (r.source_page_id=? OR r.target_page_id=?) AND sp.deleted_at IS NULL AND tp.deleted_at IS NULL ORDER BY r.created_at DESC");$s->execute([$pageId,$pageId]);return array_values(array_filter($s->fetchAll(),function(array $r)use($userId):bool{$other=$this->pages->find((int)($r['source_page_id']===$r['target_page_id']?$r['source_page_id']:$r['target_page_id']));return$other?$this->authz->canViewPage($userId,$other):false;}));
    }
    public function addRelation(int $source,int $target,string $type,int $actorId):void{$page=$this->page($source);$targetPage=$this->page($target);if(!$this->authz->canEditPage($actorId,$page)||!$this->authz->canViewPage($actorId,$targetPage))throw new AuthorizationException();if($source===$target||!in_array($type,['related_to','depends_on','replaces','duplicated_by'],true))throw new ValidationException('Invalid relation.');$this->pdo->prepare("INSERT IGNORE INTO `{$this->prefix}page_relations` (source_page_id,target_page_id,relation_type,created_by,created_at) VALUES (?,?,?,?,UTC_TIMESTAMP())")->execute([$source,$target,$type,$actorId]);}

    public function relatedSuggestions(int $pageId,int $userId,int $limit=10):array
    {
        $page=$this->page($pageId);if(!$this->authz->canViewPage($userId,$page))throw new AuthorizationException();$words=array_values(array_filter(preg_split('/\W+/u',mb_strtolower((string)$page['title']))?:[],static fn(string $w):bool=>mb_strlen($w)>=4));$where=['p.id<>?','p.deleted_at IS NULL','p.status NOT IN (\'archived\',\'expired\')'];$args=[$pageId];if($words){$parts=[];foreach(array_slice($words,0,5) as $w){$parts[]='p.title LIKE ?';$args[]='%'.$w.'%';}$where[]='('.implode(' OR ',$parts).')';}else{$where[]='p.space_id=?';$args[]=(int)$page['space_id'];}$sql="SELECT DISTINCT p.id,p.title,p.space_id,p.updated_at FROM `{$this->prefix}pages` p LEFT JOIN `{$this->prefix}page_labels` pl ON pl.page_id=p.id LEFT JOIN `{$this->prefix}page_labels` mine ON mine.page_id=? AND mine.label_id=pl.label_id WHERE ".implode(' AND ',$where)." ORDER BY (p.space_id=? ) DESC,(mine.label_id IS NOT NULL) DESC,p.updated_at DESC LIMIT ".max(1,min(30,$limit));array_unshift($args,$pageId);$args[]=(int)$page['space_id'];$s=$this->pdo->prepare($sql);$s->execute($args);return array_values(array_filter($s->fetchAll(),fn(array $r):bool=>($p=$this->pages->find((int)$r['id']))&&$this->authz->canViewPage($userId,$p)));
    }

    private function bulkStatus(array $page,string $status,int $actor):void{if(!$this->authz->canEditPage($actor,$page)&&!$this->authz->can($actor,'content.governance'))throw new AuthorizationException();if(!in_array($status,['published','archived','deprecated'],true))throw new ValidationException();$this->pdo->prepare("UPDATE `{$this->prefix}pages` SET status=?,updated_at=UTC_TIMESTAMP() WHERE id=?")->execute([$status,(int)$page['id']]);}
    private function bulkOwner(array $page,int $owner,int $actor):void{if(!$this->authz->canManagePageRestrictions($actor,$page)&&!$this->authz->can($actor,'content.governance'))throw new AuthorizationException();$u=$this->pdo->prepare("SELECT COUNT(*) FROM `{$this->prefix}users` WHERE id=? AND status='active' AND deleted_at IS NULL");$u->execute([$owner]);if((int)$u->fetchColumn()!==1)throw new ValidationException('Owner unavailable.');$this->pdo->prepare("UPDATE `{$this->prefix}pages` SET owner_id=?,updated_at=UTC_TIMESTAMP() WHERE id=?")->execute([$owner,(int)$page['id']]);}
    private function bulkDelete(array $page,int $actor):void{if(!$this->authz->canDeletePage($actor,$page))throw new AuthorizationException();if(!empty($page['legal_hold']))throw new ConflictException('Legal hold blocks deletion.');$this->pdo->prepare("UPDATE `{$this->prefix}pages` SET deleted_at=UTC_TIMESTAMP(),updated_at=UTC_TIMESTAMP() WHERE id=?")->execute([(int)$page['id']]);}
    private function addLabel(array $page,string $name,int $actor):void{if(!$this->authz->canEditPage($actor,$page))throw new AuthorizationException();$name=$this->labelName($name);$this->pdo->prepare("INSERT IGNORE INTO `{$this->prefix}labels` (name) VALUES (?)")->execute([$name]);$s=$this->pdo->prepare("SELECT id FROM `{$this->prefix}labels` WHERE name=?");$s->execute([$name]);$lid=(int)$s->fetchColumn();$this->pdo->prepare("INSERT IGNORE INTO `{$this->prefix}page_labels` (page_id,label_id) VALUES (?,?)")->execute([(int)$page['id'],$lid]);}
    private function removeLabel(array $page,string $name,int $actor):void{if(!$this->authz->canEditPage($actor,$page))throw new AuthorizationException();$s=$this->pdo->prepare("DELETE pl FROM `{$this->prefix}page_labels` pl JOIN `{$this->prefix}labels` l ON l.id=pl.label_id WHERE pl.page_id=? AND l.name=?");$s->execute([(int)$page['id'],$this->labelName($name)]);}
    private function labelName(string $name):string{$name=mb_strtolower(trim($name));if($name===''||mb_strlen($name)>100||!preg_match('/^[\pL\pN._ -]+$/u',$name))throw new ValidationException('Invalid label.');return$name;}
    private function brokenInternalLinks(int $pageId):int{$s=$this->pdo->prepare("SELECT content FROM `{$this->prefix}pages` WHERE id=?");$s->execute([$pageId]);$content=(string)$s->fetchColumn();preg_match_all('#(?:href=["\'](?:[^"\']*/)?pages/|\{\{page:)(\d+)#i',$content,$m);$count=0;foreach(array_unique(array_map('intval',$m[1]??[])) as $id){$q=$this->pdo->prepare("SELECT COUNT(*) FROM `{$this->prefix}pages` WHERE id=? AND deleted_at IS NULL");$q->execute([$id]);if((int)$q->fetchColumn()===0)$count++;}return$count;}
    private function page(int $id):array{return$this->pages->find($id)?:throw new ValidationException('Page does not exist.');}
    private function ids(array $ids,int $max):array{return array_slice(array_values(array_unique(array_filter(array_map('intval',$ids),static fn(int $v):bool=>$v>0))),0,$max);}
    private function publicReason(\Throwable $e):string{return$e instanceof AuthorizationException?'permission denied':($e instanceof ConflictException?$e->getMessage():($e instanceof ValidationException?$e->getMessage():'operation failed'));}
    private function audit(int $userId,string $action,string $type,int $id,string $description,string $category,string $severity,array $metadata=[]):void{$s=$this->pdo->prepare("INSERT INTO `{$this->prefix}audit_log` (user_id,action,category,severity,request_id,resource_type,resource_id,description,metadata_json,ip_address,user_agent,created_at) VALUES (?,?,?,?,?,?,?,?,?,'system','governance-service',UTC_TIMESTAMP())");$s->execute([$userId,$action,$category,$severity,defined('IMWIKI_REQUEST_ID')?IMWIKI_REQUEST_ID:null,$type,$id,$description,json_encode($metadata,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]);}
}
