<?php
declare(strict_types=1);
namespace ImWiki\Services;
use PDO;
final class ContentHealthService{
 public function __construct(private readonly PDO $pdo,private readonly string $prefix=''){}
 public function backlinks(int $pageId,int $limit=50):array{$needles=['%/pages/'.$pageId.'%','%/spaces/%'];$s=$this->pdo->prepare("SELECT p.id,p.title,p.updated_at,s.name space_name FROM `{$this->prefix}pages` p JOIN `{$this->prefix}spaces` s ON s.id=p.space_id WHERE p.deleted_at IS NULL AND p.id<>? AND p.content LIKE ? ORDER BY p.updated_at DESC LIMIT ".(int)min(100,$limit));$s->execute([$pageId,$needles[0]]);return $s->fetchAll();}
 public function brokenLinks():array{$pages=$this->pdo->query("SELECT id,title,content FROM `{$this->prefix}pages` WHERE deleted_at IS NULL ORDER BY id LIMIT 5000")->fetchAll();$pageIds=array_map('intval',$this->pdo->query("SELECT id FROM `{$this->prefix}pages` WHERE deleted_at IS NULL")->fetchAll(PDO::FETCH_COLUMN));$attachmentIds=array_map('intval',$this->pdo->query("SELECT id FROM `{$this->prefix}attachments` WHERE deleted_at IS NULL")->fetchAll(PDO::FETCH_COLUMN));$out=[];foreach($pages as $p){$html=(string)$p['content'];if(preg_match_all('#(?:href=["\'](?:[^"\']*)?/pages/|data-page-id=["\'])(\d+)#i',$html,$m))foreach(array_unique(array_map('intval',$m[1])) as $id)if(!in_array($id,$pageIds,true))$out[]=['page_id'=>(int)$p['id'],'title'=>$p['title'],'kind'=>'page','target'=>$id];if(preg_match_all('#(?:href=["\'](?:[^"\']*)?/attachments/)(\d+)#i',$html,$m2))foreach(array_unique(array_map('intval',$m2[1])) as $id)if(!in_array($id,$attachmentIds,true))$out[]=['page_id'=>(int)$p['id'],'title'=>$p['title'],'kind'=>'attachment','target'=>$id];}return array_slice($out,0,500);}
 public function orphanPages():array{$sql="SELECT p.id,p.title,p.updated_at,s.name space_name FROM `{$this->prefix}pages` p JOIN `{$this->prefix}spaces` s ON s.id=p.space_id LEFT JOIN `{$this->prefix}spaces` home ON home.homepage_page_id=p.id WHERE p.deleted_at IS NULL AND p.parent_id IS NULL AND home.id IS NULL AND NOT EXISTS (SELECT 1 FROM `{$this->prefix}pages` x WHERE x.deleted_at IS NULL AND x.id<>p.id AND x.content LIKE CONCAT('%/pages/',p.id,'%')) ORDER BY p.updated_at DESC LIMIT 500";return $this->pdo->query($sql)->fetchAll();}
 public function stale(int $days=180):array{$days=max(1,min(3650,$days));$s=$this->pdo->prepare("SELECT p.id,p.title,p.updated_at,p.review_date,s.name space_name,u.username owner_username FROM `{$this->prefix}pages` p JOIN `{$this->prefix}spaces` s ON s.id=p.space_id LEFT JOIN `{$this->prefix}users` u ON u.id=p.owner_id WHERE p.deleted_at IS NULL AND (p.updated_at<DATE_SUB(UTC_TIMESTAMP(),INTERVAL {$days} DAY) OR p.owner_id IS NULL OR (p.review_date IS NOT NULL AND p.review_date<CURDATE())) ORDER BY p.updated_at LIMIT 500");$s->execute();return $s->fetchAll();}
}
