<?php
declare(strict_types=1);
namespace ImWiki\Services;
use ImWiki\Repositories\PageRepository;use ImWiki\Repositories\SpaceRepository;use ImWiki\Security\Authorization;use PDO;use RuntimeException;use ZipArchive;
final class ImportExportService{
 public function __construct(private readonly PDO $pdo,private readonly string $prefix,private readonly PageRepository $pages,private readonly SpaceRepository $spaces,private readonly Authorization $authz,private readonly PageService $pageService,private readonly MarkdownService $markdown,private readonly string $root){}
 public function pageMarkdown(int $pageId,int $userId):array{$p=$this->requireView($pageId,$userId);return['name'=>$this->safeName((string)$p['title']).'.md','content'=>$this->markdown->exportDocument($p,$this->labels($pageId))];}
 public function pageHtml(int $pageId,int $userId):array{$p=$this->requireView($pageId,$userId);$title=htmlspecialchars((string)$p['title'],ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');$body=(string)$p['content'];$html='<!doctype html><html lang="pl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'.$title.'</title><style>body{font:16px/1.6 system-ui,sans-serif;max-width:900px;margin:40px auto;padding:0 20px}pre{overflow:auto;padding:12px;background:#f4f4f4}img{max-width:100%}table{border-collapse:collapse}td,th{border:1px solid #bbb;padding:6px}</style></head><body><h1>'.$title.'</h1>'.$body.'</body></html>';return['name'=>$this->safeName((string)$p['title']).'.html','content'=>$html];}
 public function spaceZip(string $key,int $userId):string{$space=$this->spaces->findByKey($key);if(!$space||!$this->authz->canViewSpace($userId,(int)$space['id']))throw new RuntimeException('FORBIDDEN');if(!class_exists(ZipArchive::class))throw new RuntimeException('ZIP_UNAVAILABLE');$tree=$this->pages->treeVisible((int)$space['id'],$userId,$this->authz->isAdmin($userId));$byId=[];foreach($tree as $row)$byId[(int)$row['id']]=$row;$tmp=tempnam($this->root.'/storage/private','export-');if($tmp===false)throw new RuntimeException('TEMP');$zip=new ZipArchive();if($zip->open($tmp,ZipArchive::OVERWRITE)!==true){@unlink($tmp);throw new RuntimeException('ZIP');}foreach($tree as $row){$page=$this->pages->find((int)$row['id']);if(!$page||!$this->authz->canViewPage($userId,$page))continue;$path=$this->treePath((int)$row['id'],$byId).'/'.$this->safeName((string)$page['title']).'.md';$zip->addFromString(ltrim($path,'/'),$this->markdown->exportDocument($page,$this->labels((int)$page['id'])));$a=$this->pdo->prepare("SELECT original_name,stored_name FROM `{$this->prefix}attachments` WHERE page_id=? AND deleted_at IS NULL");$a->execute([(int)$page['id']]);foreach($a->fetchAll() as $att){$stored=(string)$att['stored_name'];if(!preg_match('/^[a-f0-9]{48}$/',$stored))continue;$file=$this->root.'/storage/uploads/'.$stored;if(is_file($file))$zip->addFile($file,ltrim($this->treePath((int)$row['id'],$byId).'/attachments/'.$this->safeName((string)$att['original_name']),'/'));}}$zip->addFromString('metadata.json',json_encode(['space_key'=>$space['space_key'],'space_name'=>$space['name'],'exported_at'=>gmdate('c')],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));$zip->close();return$tmp;}
 public function importMarkdown(string $key,array $file,int $userId):int{$space=$this->requireCreateSpace($key,$userId);$raw=$this->uploadedText($file,2_000_000,['md','markdown']);$doc=$this->markdown->parseDocument($raw);$title=trim((string)($doc['meta']['title']??pathinfo((string)$file['name'],PATHINFO_FILENAME)));if($title==='')$title='Zaimportowana strona';return$this->pageService->create((int)$space['id'],null,$title,(string)$doc['html'],$userId);}
 public function importZip(string $key,array $file,int $userId):array{$space=$this->requireCreateSpace($key,$userId);if(!class_exists(ZipArchive::class))throw new RuntimeException('ZIP_UNAVAILABLE');$tmp=(string)($file['tmp_name']??'');if((int)($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK||!is_uploaded_file($tmp)||(int)($file['size']??0)>25_000_000)throw new \InvalidArgumentException('Nieprawidłowy ZIP.');$zip=new ZipArchive();if($zip->open($tmp)!==true)throw new \InvalidArgumentException('Nie można otworzyć ZIP.');$entries=[];$total=0;for($i=0;$i<$zip->numFiles&&count($entries)<500;$i++){$stat=$zip->statIndex($i);$name=str_replace('\\','/',(string)($stat['name']??''));if($name===''||str_starts_with($name,'/')||str_contains('/'.$name.'/','/../')||str_contains($name,"\0"))continue;if(!preg_match('/\.(md|markdown)$/i',$name))continue;$size=(int)($stat['size']??0);$total+=$size;if($size>2_000_000||$total>20_000_000){$zip->close();throw new \InvalidArgumentException('Archiwum jest zbyt duże.');}$entries[$name]=(string)$zip->getFromIndex($i);}$zip->close();uksort($entries,static fn($a,$b)=>substr_count($a,'/')<=>substr_count($b,'/'));$parents=[];$created=[];foreach($entries as $name=>$raw){$doc=$this->markdown->parseDocument($raw);$dir=trim(dirname($name),'.\/');$parent=$parents[$dir]??null;$title=trim((string)($doc['meta']['title']??pathinfo($name,PATHINFO_FILENAME)));$id=$this->pageService->create((int)$space['id'],$parent,$title!==''?$title:'Zaimportowana strona',(string)$doc['html'],$userId);$created[]=$id;$parents[trim(preg_replace('/\.(md|markdown)$/i','',$name),'/')]=$id;}return$created;}
 private function requireView(int $id,int $uid):array{$p=$this->pages->find($id);if(!$p||!$this->authz->canViewPage($uid,$p))throw new RuntimeException('FORBIDDEN');return$p;}
 private function requireCreateSpace(string $key,int $uid):array{$s=$this->spaces->findByKey($key);if(!$s||!$this->authz->canCreatePage($uid,(int)$s['id']))throw new RuntimeException('FORBIDDEN');return$s;}
 private function labels(int $pageId):array{$s=$this->pdo->prepare("SELECT l.name FROM `{$this->prefix}labels` l JOIN `{$this->prefix}page_labels` pl ON pl.label_id=l.id WHERE pl.page_id=? ORDER BY l.name");$s->execute([$pageId]);return$s->fetchAll(PDO::FETCH_COLUMN);}
 private function uploadedText(array $file,int $max,array $extensions):string{$tmp=(string)($file['tmp_name']??'');$name=(string)($file['name']??'');if((int)($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK||!is_uploaded_file($tmp)||(int)($file['size']??0)>$max||!in_array(strtolower(pathinfo($name,PATHINFO_EXTENSION)),$extensions,true))throw new \InvalidArgumentException('Nieprawidłowy plik.');$raw=file_get_contents($tmp);if($raw===false||str_contains($raw,"\0"))throw new \InvalidArgumentException('Nieprawidłowa zawartość.');return$raw;}
 private function treePath(int $id,array $byId):string{$parts=[];$seen=[];$cursor=$id;while(isset($byId[$cursor])&&!isset($seen[$cursor])&&count($parts)<50){$seen[$cursor]=1;$row=$byId[$cursor];$parts[]=$this->safeName((string)$row['title']);$cursor=(int)($row['parent_id']??0);if($cursor===0)break;}array_pop($parts);return implode('/',array_reverse($parts));}
 private function safeName(string $name):string{$name=trim(preg_replace('/[\\\\\/<>:"|?*\x00-\x1F]+/u','-',basename($name))??'page');return mb_substr($name!==''?$name:'page',0,120);}
}
