<?php
declare(strict_types=1);
namespace ImWiki\Services;
use ImWiki\Security\Html;
final class MarkdownService{
 public function toHtml(string $markdown):string{$markdown=str_replace(["\r\n","\r"],"\n",$markdown);$lines=explode("\n",$markdown);$out=[];$inCode=false;$code=[];$list=false;foreach($lines as $line){if(preg_match('/^```([a-zA-Z0-9_-]*)\s*$/',$line,$m)){if(!$inCode){if($list){$out[]='</ul>';$list=false;}$inCode=true;$code=[];$lang=$m[1]??'';}else{$class=$lang!==''?' class="language-'.htmlspecialchars($lang,ENT_QUOTES,'UTF-8').'"':'';$out[]='<pre><code'.$class.'>'.htmlspecialchars(implode("\n",$code),ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8').'</code></pre>';$inCode=false;}$lang=$m[1]??($lang??'');continue;}if($inCode){$code[]=$line;continue;}if(trim($line)===''){if($list){$out[]='</ul>';$list=false;}continue;}if(preg_match('/^(#{1,6})\s+(.+)$/',$line,$m)){$n=strlen($m[1]);$out[]='<h'.$n.'>'.$this->inline($m[2]).'</h'.$n.'>';continue;}if(preg_match('/^[-*]\s+(.+)$/',$line,$m)){if(!$list){$out[]='<ul>';$list=true;}$out[]='<li>'.$this->inline($m[1]).'</li>';continue;}if($list){$out[]='</ul>';$list=false;}if(str_starts_with(ltrim($line),'<')){$out[]=$line;}else{$out[]='<p>'.$this->inline($line).'</p>';}}if($inCode)$out[]='<pre><code>'.htmlspecialchars(implode("\n",$code),ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8').'</code></pre>';if($list)$out[]='</ul>';return Html::sanitizeRichText(implode("\n",$out));}
 public function exportDocument(array $page,array $labels=[]):string{$front=['title'=>$page['title'],'id'=>(int)$page['id'],'slug'=>$page['slug'],'space'=>$page['space_key']??null,'owner'=>$page['owner_username']??null,'status'=>$page['status']??'published','review_date'=>$page['review_date']??null,'labels'=>$labels,'updated_at'=>$page['updated_at']??null];$yaml="---\n";foreach($front as $key=>$value){if($value===null||$value==='')continue;if(is_array($value))$yaml.=$key.': ['.implode(', ',array_map(fn($v)=>$this->yamlScalar((string)$v),$value))."]\n";else$yaml.=$key.': '.$this->yamlScalar((string)$value)."\n";}return$yaml."---\n\n".(string)$page['content']."\n";}
 public function parseDocument(string $raw):array{$meta=[];$body=$raw;if(str_starts_with($raw,"---\n")){if(preg_match('/^---\n(.*?)\n---\n(.*)$/s',$raw,$m)){foreach(explode("\n",$m[1]) as $line){if(!str_contains($line,':'))continue;[$k,$v]=array_map('trim',explode(':',$line,2));if(!preg_match('/^[a-zA-Z0-9_-]+$/',$k))continue;$meta[$k]=$this->unquote($v);}$body=$m[2];}}return['meta'=>$meta,'html'=>$this->toHtml($body)];}
 private function inline(string $s):string{$s=htmlspecialchars($s,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');$s=preg_replace('/`([^`]+)`/','<code>$1</code>',$s)??$s;$s=preg_replace('/\*\*([^*]+)\*\*/','<strong>$1</strong>',$s)??$s;$s=preg_replace('/\*([^*]+)\*/','<em>$1</em>',$s)??$s;$s=preg_replace('/\[([^\]]+)\]\((https?:\/\/[^\s)]+|\/[^\s)]*)\)/','<a href="$2">$1</a>',$s)??$s;return$s;}
 private function yamlScalar(string $v):string{return '"'.str_replace(['\\','"'],['\\\\','\\"'],$v).'"';}
 private function unquote(string $v):string{$v=trim($v);if(strlen($v)>=2&&$v[0]==='"'&&$v[-1]==='"')return stripcslashes(substr($v,1,-1));return$v;}
}
