<?php
declare(strict_types=1);
namespace ImWiki\Services;
use ImWiki\Repositories\PageRepository;use ImWiki\Security\Authorization;use PDO;
final class PagePropertyService{
 public const TYPES=['text','number','date','select','user','boolean'];
 public function __construct(private readonly PDO $pdo,private readonly string $prefix,private readonly PageRepository $pages,private readonly Authorization $authz){}
 public function forPage(int $pageId):array{$stmt=$this->pdo->prepare("SELECT pp.*,u.username value_username,CONCAT(u.first_name,' ',u.last_name) value_user_name FROM `{$this->prefix}page_properties` pp LEFT JOIN `{$this->prefix}users` u ON u.id=pp.value_user_id WHERE pp.page_id=? ORDER BY pp.label,pp.id");$stmt->execute([$pageId]);$rows=$stmt->fetchAll();foreach($rows as &$r){$r['options']=$r['options_json']?json_decode((string)$r['options_json'],true)?:[]:[];$r['display_value']=$this->display($r);}unset($r);return$rows;}
 public function set(int $pageId,string $key,string $label,string $type,string $value,string $optionsText,int $actorId):void{
  $page=$this->pages->find($pageId);if(!$page||!$this->authz->canEditPage($actorId,$page))throw new \RuntimeException('FORBIDDEN');$key=mb_strtolower(trim($key));$label=trim($label);if(!preg_match('/^[a-z0-9_.-]{1,100}$/',$key)||$label===''||mb_strlen($label)>150)throw new \InvalidArgumentException('Nieprawidłowy klucz lub etykieta.');if(!in_array($type,self::TYPES,true))throw new \InvalidArgumentException('Nieprawidłowy typ właściwości.');
  $text=$number=$date=$userId=$boolean=null;$options=[];
  if($type==='text'){$text=mb_substr($value,0,5000);}elseif($type==='number'){if(!is_numeric($value))throw new \InvalidArgumentException('Wartość musi być liczbą.');$number=$value;}elseif($type==='date'){if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$value))throw new \InvalidArgumentException('Nieprawidłowa data.');$date=$value;}elseif($type==='boolean'){$boolean=in_array(mb_strtolower(trim($value)),['1','true','yes','tak','on'],true)?1:0;}elseif($type==='user'){$find=$this->pdo->prepare("SELECT id FROM `{$this->prefix}users` WHERE username=? AND status='active' AND deleted_at IS NULL");$find->execute([trim($value)]);$userId=(int)($find->fetchColumn()?:0);if($userId<=0)throw new \InvalidArgumentException('Nie znaleziono użytkownika.');}elseif($type==='select'){$options=array_values(array_unique(array_filter(array_map('trim',explode(',',$optionsText)),static fn(string $v):bool=>$v!=='')));if(!$options||count($options)>100)throw new \InvalidArgumentException('Dla select podaj listę opcji.');if(!in_array($value,$options,true))throw new \InvalidArgumentException('Wartość nie występuje na liście opcji.');$text=$value;}
  $this->pdo->beginTransaction();try{$stmt=$this->pdo->prepare("INSERT INTO `{$this->prefix}page_properties` (page_id,property_key,label,property_type,value_text,value_number,value_date,value_user_id,value_boolean,options_json,updated_by,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE label=VALUES(label),property_type=VALUES(property_type),value_text=VALUES(value_text),value_number=VALUES(value_number),value_date=VALUES(value_date),value_user_id=VALUES(value_user_id),value_boolean=VALUES(value_boolean),options_json=VALUES(options_json),updated_by=VALUES(updated_by),updated_at=UTC_TIMESTAMP()");$stmt->execute([$pageId,$key,$label,$type,$text,$number,$date,$userId,$boolean,$options?json_encode($options,JSON_UNESCAPED_UNICODE):null,$actorId]);$this->snapshotVersion($pageId,$actorId,'Zmiana właściwości: '.$label);$this->pdo->commit();}catch(\Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw$e;}
 }
 public function remove(int $pageId,int $propertyId,int $actorId):void{$page=$this->pages->find($pageId);if(!$page||!$this->authz->canEditPage($actorId,$page))throw new \RuntimeException('FORBIDDEN');$this->pdo->beginTransaction();try{$this->pdo->prepare("DELETE FROM `{$this->prefix}page_properties` WHERE id=? AND page_id=?")->execute([$propertyId,$pageId]);$this->snapshotVersion($pageId,$actorId,'Usunięcie właściwości');$this->pdo->commit();}catch(\Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw$e;}}
 private function snapshotVersion(int $pageId,int $actorId,string $comment):void{$p=$this->pdo->prepare("SELECT title,content,version_no FROM `{$this->prefix}pages` WHERE id=? FOR UPDATE");$p->execute([$pageId]);$page=$p->fetch();if(!$page)throw new \RuntimeException('Missing page.');$props=$this->pdo->prepare("SELECT property_key,label,property_type,value_text,value_number,value_date,value_user_id,value_boolean,options_json FROM `{$this->prefix}page_properties` WHERE page_id=? ORDER BY property_key");$props->execute([$pageId]);$json=json_encode($props->fetchAll(),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?:'[]';$version=(int)$page['version_no']+1;$this->pdo->prepare("UPDATE `{$this->prefix}pages` SET version_no=?,last_editor_id=?,updated_at=UTC_TIMESTAMP() WHERE id=?")->execute([$version,$actorId,$pageId]);$this->pdo->prepare("INSERT INTO `{$this->prefix}page_versions` (page_id,version_no,title,content,properties_json,author_id,change_comment,created_at) VALUES (?,?,?,?,?,?,?,UTC_TIMESTAMP())")->execute([$pageId,$version,$page['title'],$page['content'],$json,$actorId,$comment]);}
 private function display(array $r):string{return match($r['property_type']){'number'=>(string)$r['value_number'],'date'=>(string)$r['value_date'],'boolean'=>(int)$r['value_boolean']===1?'Tak':'Nie','user'=>(string)($r['value_user_name']?:$r['value_username']),'text','select'=>(string)$r['value_text'],default=>''};}
}
