<?php
declare(strict_types=1);

namespace ImWiki\Services;

use ImWiki\Exceptions\AuthorizationException;
use ImWiki\Exceptions\ValidationException;
use ImWiki\Repositories\PageRepository;
use ImWiki\Security\Authorization;
use PDO;

final class PropertySchemaService
{
    public const TYPES=['text','textarea','integer','decimal','date','datetime','select','multiselect','user','group','boolean','url'];
    public function __construct(private readonly PDO $pdo,private readonly string $prefix,private readonly Authorization $authz,private readonly PageRepository $pages){}

    public function schemas(int $userId,?int $spaceId=null):array
    {
        if($spaceId!==null&&!$this->authz->canViewSpace($userId,$spaceId))throw new AuthorizationException();$sql="SELECT ps.*,s.space_key FROM `{$this->prefix}property_schemas` ps LEFT JOIN `{$this->prefix}spaces` s ON s.id=ps.space_id WHERE ps.enabled=1"; $args=[];if($spaceId!==null){$sql.=' AND (ps.space_id IS NULL OR ps.space_id=?)';$args[]=$spaceId;}$sql.=' ORDER BY ps.space_id IS NOT NULL,ps.name,ps.version_no DESC';$stmt=$this->pdo->prepare($sql);$stmt->execute($args);return$stmt->fetchAll()?:[];
    }

    public function schema(int $id,int $userId):?array
    {
        $s=$this->pdo->prepare("SELECT * FROM `{$this->prefix}property_schemas` WHERE id=?");$s->execute([$id]);$schema=$s->fetch();if(!$schema)return null;if($schema['space_id']!==null&&!$this->authz->canViewSpace($userId,(int)$schema['space_id']))throw new AuthorizationException();$f=$this->pdo->prepare("SELECT * FROM `{$this->prefix}property_schema_fields` WHERE schema_id=? ORDER BY sort_order,id");$f->execute([$id]);$schema['fields']=$f->fetchAll();return$schema;
    }

    public function create(int $actorId,?int $spaceId,string $name,string $description,array $fields):int
    {
        $this->authorizeSchemaManage($actorId,$spaceId);$name=trim($name);if($name===''||mb_strlen($name)>150)throw new ValidationException('Invalid schema name.');$clean=$this->validateFields($fields);$this->pdo->beginTransaction();try{$stmt=$this->pdo->prepare("INSERT INTO `{$this->prefix}property_schemas` (space_id,name,description,version_no,enabled,created_by,created_at,updated_at) VALUES (?,?,?,1,1,?,UTC_TIMESTAMP(),UTC_TIMESTAMP())");$stmt->execute([$spaceId,$name,mb_substr(trim($description),0,500),$actorId]);$id=(int)$this->pdo->lastInsertId();$this->insertFields($id,$clean);$this->pdo->commit();return$id;}catch(\Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw$e;}
    }

    public function newVersion(int $schemaId,int $actorId,array $fields,?string $description=null):int
    {
        $old=$this->schema($schemaId,$actorId);if(!$old)throw new ValidationException('Unknown schema.');$spaceId=$old['space_id']!==null?(int)$old['space_id']:null;$this->authorizeSchemaManage($actorId,$spaceId);$clean=$this->validateFields($fields);$this->pdo->beginTransaction();try{$max=$this->pdo->prepare("SELECT MAX(version_no) FROM `{$this->prefix}property_schemas` WHERE space_id<=>? AND name=?");$max->execute([$spaceId,$old['name']]);$version=(int)$max->fetchColumn()+1;$stmt=$this->pdo->prepare("INSERT INTO `{$this->prefix}property_schemas` (space_id,name,description,version_no,enabled,created_by,created_at,updated_at) VALUES (?,?,?,?,1,?,UTC_TIMESTAMP(),UTC_TIMESTAMP())");$stmt->execute([$spaceId,$old['name'],$description!==null?mb_substr(trim($description),0,500):$old['description'],$version,$actorId]);$id=(int)$this->pdo->lastInsertId();$this->insertFields($id,$clean);$this->pdo->commit();return$id;}catch(\Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw$e;}
    }

    public function assign(int $pageId,int $schemaId,int $actorId):void
    {
        $page=$this->pages->find($pageId);if(!$page||!$this->authz->canEditPage($actorId,$page))throw new AuthorizationException();$schema=$this->schema($schemaId,$actorId);if(!$schema||($schema['space_id']!==null&&(int)$schema['space_id']!==(int)$page['space_id']))throw new ValidationException('Schema cannot be used in this Space.');$this->pdo->prepare("UPDATE `{$this->prefix}pages` SET property_schema_id=?,updated_at=UTC_TIMESTAMP() WHERE id=?")->execute([$schemaId,$pageId]);
    }

    public function setValues(int $pageId,array $values,int $actorId):void
    {
        $page=$this->pages->find($pageId);if(!$page||!$this->authz->canEditPage($actorId,$page))throw new AuthorizationException();$schemaId=(int)($page['property_schema_id']??0);if($schemaId<=0)throw new ValidationException('Page has no property schema.');$schema=$this->schema($schemaId,$actorId);if(!$schema)throw new ValidationException('Schema missing.');$byKey=[];foreach($schema['fields'] as $f)$byKey[(string)$f['field_key']]=$f;
        $this->pdo->beginTransaction();try{foreach($byKey as $key=>$field){$raw=$values[$key]??null;if((bool)$field['required']&&($raw===null||$raw===''||$raw===[]))throw new ValidationException('Required property: '.$field['label']);$norm=$this->normalizeValue($field,$raw);$stmt=$this->pdo->prepare("INSERT INTO `{$this->prefix}page_properties` (page_id,schema_field_id,property_key,label,property_type,value_text,value_number,value_date,value_datetime,value_user_id,value_group_id,value_boolean,value_json,options_json,updated_by,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE schema_field_id=VALUES(schema_field_id),label=VALUES(label),property_type=VALUES(property_type),value_text=VALUES(value_text),value_number=VALUES(value_number),value_date=VALUES(value_date),value_datetime=VALUES(value_datetime),value_user_id=VALUES(value_user_id),value_group_id=VALUES(value_group_id),value_boolean=VALUES(value_boolean),value_json=VALUES(value_json),options_json=VALUES(options_json),updated_by=VALUES(updated_by),updated_at=UTC_TIMESTAMP()");$stmt->execute([$pageId,(int)$field['id'],$key,$field['label'],$field['field_type'],$norm['text'],$norm['number'],$norm['date'],$norm['datetime'],$norm['user'],$norm['group'],$norm['boolean'],$norm['json'],$field['options_json'],$actorId]);}$this->pdo->commit();}catch(\Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw$e;}
    }

    public function report(int $schemaId,int $userId,array $filters=[],int $page=1,int $perPage=50):array
    {
        $schema=$this->schema($schemaId,$userId);if(!$schema)throw new ValidationException('Unknown schema.');$page=max(1,$page);$perPage=max(1,min(100,$perPage));$where=['p.property_schema_id=?','p.deleted_at IS NULL'];$args=[$schemaId];if(!empty($filters['space_id'])){$where[]='p.space_id=?';$args[]=(int)$filters['space_id'];}if(!empty($filters['owner_id'])){$where[]='p.owner_id=?';$args[]=(int)$filters['owner_id'];}if(!empty($filters['status'])){$where[]='p.status=?';$args[]=(string)$filters['status'];}if(!empty($filters['label'])){$where[]="EXISTS (SELECT 1 FROM `{$this->prefix}page_labels` pl JOIN `{$this->prefix}labels` l ON l.id=pl.label_id WHERE pl.page_id=p.id AND l.name=?)";$args[]=mb_strtolower(trim((string)$filters['label']));}if(!empty($filters['property_key'])&&isset($filters['property_value'])){$where[]="EXISTS (SELECT 1 FROM `{$this->prefix}page_properties` pp WHERE pp.page_id=p.id AND pp.property_key=? AND COALESCE(pp.value_text,CAST(pp.value_number AS CHAR),CAST(pp.value_date AS CHAR),CAST(pp.value_datetime AS CHAR),CAST(pp.value_boolean AS CHAR)) LIKE ?)";$args[]=(string)$filters['property_key'];$args[]='%'.(string)$filters['property_value'].'%';}
        $sql="SELECT p.id,p.uuid,p.title,p.status,p.owner_id,p.space_id,s.name space_name,s.space_key,u.username owner_username FROM `{$this->prefix}pages` p JOIN `{$this->prefix}spaces` s ON s.id=p.space_id LEFT JOIN `{$this->prefix}users` u ON u.id=p.owner_id WHERE ".implode(' AND ',$where)." ORDER BY p.title LIMIT ".$perPage.' OFFSET '.(($page-1)*$perPage);$stmt=$this->pdo->prepare($sql);$stmt->execute($args);$rows=[];foreach($stmt->fetchAll() as $row){$full=$this->pages->find((int)$row['id']);if(!$full||!$this->authz->canViewPage($userId,$full))continue;$props=$this->pdo->prepare("SELECT property_key,property_type,value_text,value_number,value_date,value_datetime,value_user_id,value_group_id,value_boolean,value_json FROM `{$this->prefix}page_properties` WHERE page_id=?");$props->execute([(int)$row['id']]);$row['properties']=[];foreach($props->fetchAll() as $prop)$row['properties'][$prop['property_key']]=$this->displayValue($prop);$rows[]=$row;}return['items'=>$rows,'page'=>$page,'per_page'=>$perPage,'next'=>count($rows)===$perPage?$page+1:null,'schema'=>$schema];
    }

    private function authorizeSchemaManage(int $actor,?int $spaceId):void{if($spaceId===null){if(!$this->authz->can($actor,'content.governance'))throw new AuthorizationException();}elseif(!$this->authz->canManageSpace($actor,$spaceId))throw new AuthorizationException();}
    private function validateFields(array $fields):array{$out=[];$keys=[];foreach(array_slice($fields,0,100) as $i=>$field){if(!is_array($field))continue;$key=mb_strtolower(trim((string)($field['key']??$field['field_key']??'')));$label=trim((string)($field['label']??''));$type=(string)($field['type']??$field['field_type']??'text');if(!preg_match('/^[a-z][a-z0-9_.-]{1,99}$/',$key)||isset($keys[$key])||$label===''||mb_strlen($label)>150||!in_array($type,self::TYPES,true))throw new ValidationException('Invalid schema field.');$keys[$key]=true;$options=[];if(in_array($type,['select','multiselect'],true)){$raw=(array)($field['options']??[]);foreach(array_slice($raw,0,200) as $v){$v=trim((string)$v);if($v!==''&&mb_strlen($v)<=150)$options[]=$v;}$options=array_values(array_unique($options));if(!$options)throw new ValidationException('Select field requires options.');}$out[]=['key'=>$key,'label'=>$label,'type'=>$type,'required'=>!empty($field['required']),'options'=>$options,'sort'=>(int)($field['sort_order']??(($i+1)*10))];}if(!$out)throw new ValidationException('Schema requires at least one field.');return$out;}
    private function insertFields(int $schemaId,array $fields):void{$stmt=$this->pdo->prepare("INSERT INTO `{$this->prefix}property_schema_fields` (schema_id,field_key,label,field_type,required,options_json,sort_order) VALUES (?,?,?,?,?,?,?)");foreach($fields as $f)$stmt->execute([$schemaId,$f['key'],$f['label'],$f['type'],$f['required']?1:0,$f['options']?json_encode($f['options'],JSON_THROW_ON_ERROR|JSON_UNESCAPED_UNICODE):null,$f['sort']]);}
    private function normalizeValue(array $field,mixed $raw):array{$v=['text'=>null,'number'=>null,'date'=>null,'datetime'=>null,'user'=>null,'group'=>null,'boolean'=>null,'json'=>null];$type=(string)$field['field_type'];if($raw===null||$raw==='')return$v;switch($type){case'text':case'textarea':$text=trim((string)$raw);if(mb_strlen($text)>($type==='textarea'?10000:2000))throw new ValidationException('Property is too long.');$v['text']=$text;break;case'url':$text=trim((string)$raw);if(!filter_var($text,FILTER_VALIDATE_URL)||!preg_match('#^https?://#i',$text))throw new ValidationException('Invalid URL property.');$v['text']=$text;break;case'integer':if(filter_var($raw,FILTER_VALIDATE_INT)===false)throw new ValidationException('Invalid integer.');$v['number']=(int)$raw;break;case'decimal':if(!is_numeric($raw))throw new ValidationException('Invalid decimal.');$v['number']=(string)$raw;break;case'date':$d=(string)$raw;if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$d)||strtotime($d)===false)throw new ValidationException('Invalid date.');$v['date']=$d;break;case'datetime':$ts=strtotime((string)$raw);if($ts===false)throw new ValidationException('Invalid datetime.');$v['datetime']=gmdate('Y-m-d H:i:s',$ts);break;case'boolean':$v['boolean']=filter_var($raw,FILTER_VALIDATE_BOOL)?1:0;break;case'user':$id=(int)$raw;$q=$this->pdo->prepare("SELECT COUNT(*) FROM `{$this->prefix}users` WHERE id=? AND deleted_at IS NULL");$q->execute([$id]);if((int)$q->fetchColumn()!==1)throw new ValidationException('Unknown user property.');$v['user']=$id;break;case'group':$id=(int)$raw;$q=$this->pdo->prepare("SELECT COUNT(*) FROM `{$this->prefix}groups` WHERE id=?");$q->execute([$id]);if((int)$q->fetchColumn()!==1)throw new ValidationException('Unknown group property.');$v['group']=$id;break;case'select':$text=(string)$raw;$options=json_decode((string)($field['options_json']??'[]'),true)?:[];if(!in_array($text,$options,true))throw new ValidationException('Invalid select option.');$v['text']=$text;break;case'multiselect':$values=is_array($raw)?array_values(array_unique(array_map('strval',$raw))):[];$options=json_decode((string)($field['options_json']??'[]'),true)?:[];if(array_diff($values,$options))throw new ValidationException('Invalid multiselect option.');$v['json']=json_encode($values,JSON_THROW_ON_ERROR|JSON_UNESCAPED_UNICODE);break;}return$v;}
    private function displayValue(array $p):mixed{return match((string)$p['property_type']){'integer','decimal','number'=>$p['value_number'],'date'=>$p['value_date'],'datetime'=>$p['value_datetime'],'user'=>$p['value_user_id'],'group'=>$p['value_group_id'],'boolean'=>(bool)$p['value_boolean'],'multiselect'=>json_decode((string)($p['value_json']??'[]'),true)?:[],default=>$p['value_text']};}
}
