<?php
declare(strict_types=1);
namespace ImWiki\Services;
use ImWiki\Repositories\SpaceRepository;use ImWiki\Security\Authorization;use PDO;use RuntimeException;
final class SpaceManagementService{
 public function __construct(private readonly PDO $pdo,private readonly string $prefix,private readonly SpaceRepository $spaces,private readonly Authorization $authz){}
 public function update(string $key,int $actorId,array $input):void{$space=$this->spaces->findByKey($key);if(!$space||!$this->authz->canManageSpace($actorId,(int)$space['id']))throw new RuntimeException('FORBIDDEN');$name=trim((string)($input['name']??''));$description=trim((string)($input['description']??''));$visibility=(string)($input['visibility']??'logged_in');if($name===''||mb_strlen($name)>190||!in_array($visibility,['logged_in','private','restricted'],true))throw new \InvalidArgumentException('Nieprawidłowe ustawienia Space.');$homepage=(int)($input['homepage_page_id']??0);if($homepage>0){$q=$this->pdo->prepare("SELECT COUNT(*) FROM `{$this->prefix}pages` WHERE id=? AND space_id=? AND deleted_at IS NULL");$q->execute([$homepage,(int)$space['id']]);if((int)$q->fetchColumn()!==1)throw new \InvalidArgumentException('Homepage musi należeć do tego Space.');}else $homepage=null;$sidebar=$this->normalizeSidebar((string)($input['sidebar_json']??''));$stmt=$this->pdo->prepare("UPDATE `{$this->prefix}spaces` SET name=?,description=?,visibility=?,homepage_page_id=?,sidebar_config_json=?,updated_at=UTC_TIMESTAMP() WHERE id=?");$stmt->execute([$name,$description,$visibility,$homepage,$sidebar?json_encode($sidebar,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES):null,(int)$space['id']]);}
 public function archive(string $key,int $actorId,bool $archive):void{$space=$this->spaces->findByKey($key);if(!$space||!$this->authz->canManageSpace($actorId,(int)$space['id']))throw new RuntimeException('FORBIDDEN');$stmt=$this->pdo->prepare("UPDATE `{$this->prefix}spaces` SET archived_at=".($archive?'UTC_TIMESTAMP()':'NULL').",updated_at=UTC_TIMESTAMP() WHERE id=?");$stmt->execute([(int)$space['id']]);}
 public function sidebar(array $space):array{$raw=$space['sidebar_config_json']??null;$v=$raw?json_decode((string)$raw,true):[];return is_array($v)?$v:[];}
 private function normalizeSidebar(string $json):array{if(trim($json)==='')return[];$data=json_decode($json,true);if(!is_array($data))throw new \InvalidArgumentException('Konfiguracja sidebaru musi być JSON.');$out=[];foreach(array_slice($data,0,20) as $item){if(!is_array($item))continue;$label=mb_substr(trim((string)($item['label']??'')),0,100);$url=trim((string)($item['url']??''));if($label===''||$url==='')continue;if(str_starts_with($url,'/')){$type='internal';}elseif(filter_var($url,FILTER_VALIDATE_URL)&&in_array(strtolower((string)parse_url($url,PHP_URL_SCHEME)),['http','https'],true)){$type='external';}else continue;$out[]=['label'=>$label,'url'=>$url,'type'=>$type];}return$out;}
}
