<?php
declare(strict_types=1);
namespace ImWiki\Services;
use ImWiki\Security\Authorization;use ImWiki\Security\Html;use PDO;use RuntimeException;
final class TemplateService{
 public function __construct(private readonly PDO $pdo,private readonly string $prefix,private readonly Authorization $authz){}
 public function available(int $userId,?int $spaceId=null):array{$sql="SELECT t.*,s.name space_name FROM `{$this->prefix}templates` t LEFT JOIN `{$this->prefix}spaces` s ON s.id=t.space_id WHERE t.archived_at IS NULL AND (t.space_id IS NULL";$args=[];if($spaceId!==null){$sql.=' OR t.space_id=?';$args[]=$spaceId;}$sql.=') ORDER BY t.is_system DESC,t.name';$st=$this->pdo->prepare($sql);$st->execute($args);$out=[];foreach($st->fetchAll() as $row){if($row['space_id']===null||$this->authz->canViewSpace($userId,(int)$row['space_id']))$out[]=$row;}return$out;}
 public function allManageable(int $userId):array{$rows=$this->pdo->query("SELECT t.*,s.name space_name FROM `{$this->prefix}templates` t LEFT JOIN `{$this->prefix}spaces` s ON s.id=t.space_id ORDER BY t.archived_at IS NOT NULL,t.name")->fetchAll();return array_values(array_filter($rows,fn($r)=>$r['space_id']===null?$this->authz->can($userId,'administration.access'):$this->authz->canManageSpace($userId,(int)$r['space_id'])));}
 public function find(int $id,int $userId):?array{$s=$this->pdo->prepare("SELECT * FROM `{$this->prefix}templates` WHERE id=?");$s->execute([$id]);$t=$s->fetch();if(!$t)return null;if($t['space_id']!==null&&!$this->authz->canViewSpace($userId,(int)$t['space_id']))return null;return$t;}
 public function create(int $userId,?int $spaceId,array $d):int{$this->guardManage($userId,$spaceId);$name=trim((string)($d['name']??''));if($name===''||mb_strlen($name)>150)throw new RuntimeException('Invalid name.');$content=Html::sanitizeRichText((string)($d['content']??''));$labels=$this->labels((string)($d['labels']??''));$properties=$this->properties((string)($d['properties']??''));$s=$this->pdo->prepare("INSERT INTO `{$this->prefix}templates` (space_id,name,description,content,labels_json,properties_json,is_system,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,0,?,UTC_TIMESTAMP(),UTC_TIMESTAMP())");$s->execute([$spaceId,$name,mb_substr(trim((string)($d['description']??'')),0,255),$content,json_encode($labels,JSON_UNESCAPED_UNICODE),json_encode($properties,JSON_UNESCAPED_UNICODE),$userId]);return(int)$this->pdo->lastInsertId();}
 public function update(int $id,int $userId,array $d):void{$t=$this->raw($id);if(!$t)throw new RuntimeException('Missing.');$this->guardManage($userId,$t['space_id']!==null?(int)$t['space_id']:null);$name=trim((string)($d['name']??''));if($name==='')throw new RuntimeException('Invalid.');$this->pdo->prepare("UPDATE `{$this->prefix}templates` SET name=?,description=?,content=?,labels_json=?,properties_json=?,updated_at=UTC_TIMESTAMP() WHERE id=? AND is_system=0")->execute([$name,mb_substr(trim((string)($d['description']??'')),0,255),Html::sanitizeRichText((string)($d['content']??'')),json_encode($this->labels((string)($d['labels']??'')),JSON_UNESCAPED_UNICODE),json_encode($this->properties((string)($d['properties']??'')),JSON_UNESCAPED_UNICODE),$id]);}

 public function applyToPage(int $templateId,int $pageId,int $userId):void{$t=$this->find($templateId,$userId);if(!$t||$t['archived_at']!==null)throw new RuntimeException('Template unavailable.');$labels=json_decode((string)($t['labels_json']??'[]'),true)?:[];foreach($labels as $label){$label=mb_substr(trim((string)$label),0,100);if($label==='')continue;$this->pdo->prepare("INSERT IGNORE INTO `{$this->prefix}labels` (name) VALUES (?)")->execute([$label]);$q=$this->pdo->prepare("SELECT id FROM `{$this->prefix}labels` WHERE name=?");$q->execute([$label]);$lid=(int)$q->fetchColumn();if($lid>0)$this->pdo->prepare("INSERT IGNORE INTO `{$this->prefix}page_labels` (page_id,label_id) VALUES (?,?)")->execute([$pageId,$lid]);}
  $properties=json_decode((string)($t['properties_json']??'[]'),true)?:[];$normalized=[];if(array_is_list($properties)){$normalized=$properties;}else{foreach($properties as $key=>$value)$normalized[]=['key'=>(string)$key,'label'=>ucfirst((string)$key),'type'=>'text','value'=>(string)$value];}
  foreach($normalized as $property){if(!is_array($property))continue;$key=mb_strtolower(trim((string)($property['key']??'')));$label=trim((string)($property['label']??$key));$type=(string)($property['type']??'text');$value=(string)($property['value']??'');$options=$property['options']??[];if(!preg_match('/^[a-z0-9_.-]{1,100}$/',$key)||$label===''||!in_array($type,PagePropertyService::TYPES,true))continue;$text=$number=$date=$valueUser=$boolean=null;$optionsJson=null;if($type==='text')$text=mb_substr($value,0,5000);elseif($type==='number'&&is_numeric($value))$number=$value;elseif($type==='date'&&preg_match('/^\d{4}-\d{2}-\d{2}$/',$value))$date=$value;elseif($type==='boolean')$boolean=in_array(mb_strtolower($value),['1','true','yes','tak','on'],true)?1:0;elseif($type==='select'&&is_array($options)){$clean=array_values(array_unique(array_filter(array_map(static fn($v)=>trim((string)$v),$options))));if($clean&&in_array($value,$clean,true)){$text=$value;$optionsJson=json_encode($clean,JSON_UNESCAPED_UNICODE);}}elseif($type==='user'){$q=$this->pdo->prepare("SELECT id FROM `{$this->prefix}users` WHERE username=? AND status='active' AND deleted_at IS NULL");$q->execute([$value]);$valueUser=(int)($q->fetchColumn()?:0);if($valueUser<=0)continue;}else{if($type!=='text'&&$type!=='boolean')continue;}
   $stmt=$this->pdo->prepare("INSERT INTO `{$this->prefix}page_properties` (page_id,property_key,label,property_type,value_text,value_number,value_date,value_user_id,value_boolean,options_json,updated_by,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE label=VALUES(label),property_type=VALUES(property_type),value_text=VALUES(value_text),value_number=VALUES(value_number),value_date=VALUES(value_date),value_user_id=VALUES(value_user_id),value_boolean=VALUES(value_boolean),options_json=VALUES(options_json),updated_by=VALUES(updated_by),updated_at=UTC_TIMESTAMP()");$stmt->execute([$pageId,$key,mb_substr($label,0,150),$type,$text,$number,$date,$valueUser,$boolean,$optionsJson,$userId]);}  $snap=$this->pdo->prepare("SELECT property_key,label,property_type,value_text,value_number,value_date,value_user_id,value_boolean,options_json FROM `{$this->prefix}page_properties` WHERE page_id=? ORDER BY property_key");$snap->execute([$pageId]);$this->pdo->prepare("UPDATE `{$this->prefix}page_versions` SET properties_json=? WHERE page_id=? AND version_no=1")->execute([json_encode($snap->fetchAll(),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?:'[]',$pageId]);
 }
 public function cloneTemplate(int $id,int $userId):int{$t=$this->raw($id);if(!$t)throw new RuntimeException('Missing.');$space=$t['space_id']!==null?(int)$t['space_id']:null;$this->guardManage($userId,$space);$s=$this->pdo->prepare("INSERT INTO `{$this->prefix}templates` (space_id,name,description,content,labels_json,properties_json,is_system,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,0,?,UTC_TIMESTAMP(),UTC_TIMESTAMP())");$s->execute([$space,'Kopia — '.$t['name'],$t['description'],$t['content'],$t['labels_json'],$t['properties_json'],$userId]);return(int)$this->pdo->lastInsertId();}
 public function archive(int $id,int $userId):void{$t=$this->raw($id);if(!$t)throw new RuntimeException('Missing.');$this->guardManage($userId,$t['space_id']!==null?(int)$t['space_id']:null);if((int)$t['is_system']===1)throw new RuntimeException('System template.');$this->pdo->prepare("UPDATE `{$this->prefix}templates` SET archived_at=UTC_TIMESTAMP(),updated_at=UTC_TIMESTAMP() WHERE id=?")->execute([$id]);}
 private function raw(int $id):?array{$s=$this->pdo->prepare("SELECT * FROM `{$this->prefix}templates` WHERE id=?");$s->execute([$id]);return$s->fetch()?:null;}
 private function guardManage(int $uid,?int $sid):void{if($sid===null){if(!$this->authz->can($uid,'administration.access'))throw new RuntimeException('Forbidden.');}elseif(!$this->authz->canManageSpace($uid,$sid))throw new RuntimeException('Forbidden.');}
 private function labels(string $v):array{return array_values(array_slice(array_unique(array_filter(array_map('trim',explode(',',$v)))),0,50));}
 private function properties(string $v):array{if(trim($v)==='')return[];$d=json_decode($v,true);if(!is_array($d))throw new RuntimeException('Properties must be JSON.');return$d;}
}
