<?php
declare(strict_types=1);
namespace ImWiki\Services;
use PDO;use RuntimeException;
final class UserManagementService{
 public function __construct(private readonly PDO $pdo,private readonly string $prefix,private readonly SessionService $sessions){}
 public function roles():array{return $this->pdo->query("SELECT id,name,label FROM `{$this->prefix}roles` ORDER BY label")->fetchAll();}
 public function groups():array{return $this->pdo->query("SELECT g.*,COUNT(gu.user_id) member_count FROM `{$this->prefix}groups` g LEFT JOIN `{$this->prefix}group_users` gu ON gu.group_id=g.id GROUP BY g.id ORDER BY g.label")->fetchAll();}
 public function group(int $id):?array{$s=$this->pdo->prepare("SELECT * FROM `{$this->prefix}groups` WHERE id=?");$s->execute([$id]);$g=$s->fetch();if(!$g)return null;$m=$this->pdo->prepare("SELECT u.id,u.username,u.first_name,u.last_name,u.email FROM `{$this->prefix}users` u JOIN `{$this->prefix}group_users` gu ON gu.user_id=u.id WHERE gu.group_id=? AND u.deleted_at IS NULL ORDER BY u.username");$m->execute([$id]);$g['members']=$m->fetchAll();return $g;}
 public function users(string $query,int $page,int $perPage=25):array{$page=max(1,$page);$perPage=max(1,min(100,$perPage));$where="deleted_at IS NULL";$args=[];if($query!==''){$where.=" AND (username LIKE ? OR email LIKE ? OR first_name LIKE ? OR last_name LIKE ?)";$like='%'.$query.'%';$args=[$like,$like,$like,$like];}$c=$this->pdo->prepare("SELECT COUNT(*) FROM `{$this->prefix}users` WHERE {$where}");$c->execute($args);$total=(int)$c->fetchColumn();$stmt=$this->pdo->prepare("SELECT id,username,first_name,last_name,email,status,force_password_change,last_login_at,created_at FROM `{$this->prefix}users` WHERE {$where} ORDER BY created_at DESC LIMIT ".(int)$perPage." OFFSET ".(($page-1)*$perPage));$stmt->execute($args);return ['items'=>$stmt->fetchAll(),'total'=>$total,'page'=>$page,'pages'=>max(1,(int)ceil($total/$perPage))];}
 public function user(int $id):?array{$s=$this->pdo->prepare("SELECT * FROM `{$this->prefix}users` WHERE id=? AND deleted_at IS NULL");$s->execute([$id]);$u=$s->fetch();if(!$u)return null;$r=$this->pdo->prepare("SELECT role_id FROM `{$this->prefix}user_roles` WHERE user_id=?");$r->execute([$id]);$u['role_ids']=array_map('intval',$r->fetchAll(PDO::FETCH_COLUMN));return $u;}
 public function create(array $d):int{$username=trim((string)($d['username']??''));$email=strtolower(trim((string)($d['email']??'')));$pass=(string)($d['password']??'');if(!preg_match('/^[A-Za-z0-9._-]{3,100}$/',$username)||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($email)>190||strlen($pass)<10)throw new RuntimeException('Invalid user data.');$this->pdo->beginTransaction();try{$s=$this->pdo->prepare("INSERT INTO `{$this->prefix}users` (username,first_name,last_name,email,password_hash,status,force_password_change,language,timezone,theme,created_at,updated_at) VALUES (?,?,?,?,?,'active',?,'pl','Europe/Warsaw','system',UTC_TIMESTAMP(),UTC_TIMESTAMP())");$s->execute([$username,trim((string)($d['first_name']??'')),trim((string)($d['last_name']??'')),$email,password_hash($pass,PASSWORD_DEFAULT),!empty($d['force_password_change'])?1:0]);$id=(int)$this->pdo->lastInsertId();$this->setRoles($id,(array)($d['roles']??[]));$this->pdo->commit();return $id;}catch(\Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}}
 public function update(int $id,array $d):void{$username=trim((string)($d['username']??''));$email=strtolower(trim((string)($d['email']??'')));$status=(string)($d['status']??'active');if(!preg_match('/^[A-Za-z0-9._-]{3,100}$/',$username)||!filter_var($email,FILTER_VALIDATE_EMAIL)||!in_array($status,['active','blocked','disabled'],true))throw new RuntimeException('Invalid user data.');$this->pdo->beginTransaction();try{$s=$this->pdo->prepare("UPDATE `{$this->prefix}users` SET username=?,first_name=?,last_name=?,email=?,status=?,force_password_change=?,updated_at=UTC_TIMESTAMP() WHERE id=? AND deleted_at IS NULL");$s->execute([$username,trim((string)($d['first_name']??'')),trim((string)($d['last_name']??'')),$email,$status,!empty($d['force_password_change'])?1:0,$id]);$this->setRoles($id,(array)($d['roles']??[]));$this->pdo->commit();if($status!=='active')$this->sessions->revokeAllForUser($id);}catch(\Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}}
 public function resetPassword(int $id,string $password):void{if(strlen($password)<10)throw new RuntimeException('Password too short.');$s=$this->pdo->prepare("UPDATE `{$this->prefix}users` SET password_hash=?,force_password_change=1,updated_at=UTC_TIMESTAMP() WHERE id=? AND deleted_at IS NULL");$s->execute([password_hash($password,PASSWORD_DEFAULT),$id]);$this->sessions->revokeAllForUser($id);}
 public function delete(int $id,int $actorId):void{if($id===$actorId)throw new RuntimeException('Cannot delete current user.');$this->pdo->prepare("UPDATE `{$this->prefix}users` SET status='disabled',deleted_at=UTC_TIMESTAMP(),updated_at=UTC_TIMESTAMP() WHERE id=? AND deleted_at IS NULL")->execute([$id]);$this->sessions->revokeAllForUser($id);}
 public function createGroup(string $name,string $label):int{$name=strtolower(trim($name));$label=trim($label);if(!preg_match('/^[a-z0-9._-]{2,100}$/',$name)||$label===''||mb_strlen($label)>150)throw new RuntimeException('Invalid group.');$s=$this->pdo->prepare("INSERT INTO `{$this->prefix}groups` (name,label,created_at,updated_at) VALUES (?,?,UTC_TIMESTAMP(),UTC_TIMESTAMP())");$s->execute([$name,$label]);return (int)$this->pdo->lastInsertId();}
 public function updateGroup(int $id,string $name,string $label):void{$current=$this->groupMeta($id);if(!$current)throw new RuntimeException('Unknown group.');if((bool)$current['system'])throw new RuntimeException('System group cannot be renamed.');$name=strtolower(trim($name));$label=trim($label);if(!preg_match('/^[a-z0-9._-]{2,100}$/',$name)||$label==='')throw new RuntimeException('Invalid group.');$this->pdo->prepare("UPDATE `{$this->prefix}groups` SET name=?,label=?,updated_at=UTC_TIMESTAMP() WHERE id=?")->execute([$name,$label,$id]);}
 public function deleteGroup(int $id):void{$current=$this->groupMeta($id);if(!$current)return;if((bool)$current['system'])throw new RuntimeException('System group cannot be deleted.');$this->pdo->prepare("DELETE FROM `{$this->prefix}groups` WHERE id=?")->execute([$id]);}
 public function addGroupMember(int $groupId,string $username):void{$s=$this->pdo->prepare("SELECT id FROM `{$this->prefix}users` WHERE username=? AND deleted_at IS NULL");$s->execute([trim($username)]);$uid=(int)($s->fetchColumn()?:0);if($uid<=0)throw new RuntimeException('Unknown user.');$this->pdo->prepare("INSERT IGNORE INTO `{$this->prefix}group_users` (group_id,user_id) VALUES (?,?)")->execute([$groupId,$uid]);}
 public function removeGroupMember(int $groupId,int $userId):void{$this->pdo->prepare("DELETE FROM `{$this->prefix}group_users` WHERE group_id=? AND user_id=?")->execute([$groupId,$userId]);}
 private function groupMeta(int $id):?array{$s=$this->pdo->prepare("SELECT id,name,`system` FROM `{$this->prefix}groups` WHERE id=? LIMIT 1");$s->execute([$id]);return$s->fetch()?:null;}
 private function setRoles(int $id,array $roles):void{$roles=array_values(array_unique(array_map('intval',$roles)));$this->pdo->prepare("DELETE FROM `{$this->prefix}user_roles` WHERE user_id=?")->execute([$id]);if(!$roles)return;$allowed=$this->pdo->query("SELECT id FROM `{$this->prefix}roles`")->fetchAll(PDO::FETCH_COLUMN);$allowed=array_map('intval',$allowed);$ins=$this->pdo->prepare("INSERT INTO `{$this->prefix}user_roles` (user_id,role_id) VALUES (?,?)");foreach($roles as $rid)if(in_array($rid,$allowed,true))$ins->execute([$id,$rid]);}
}
