<?php
use ImWiki\Security\Csrf;
use ImWiki\Security\Html;
use ImWiki\Support\Url;
$editing=(bool)$page;$title=$editing?'Edytuj stronę':'Nowa strona';
?>
<div class="page-head"><div><p class="eyebrow"><?=Html::e($space['name'])?></p><h1><?=$editing?'Edytuj stronę':'Nowa strona'?></h1><p class="muted">Wpisz <code>@username</code>, aby wspomnieć użytkownika.</p></div></div>
<?php if($error):?><div class="alert danger"><?=Html::e($error)?></div><?php endif;?>
<form method="post" class="editor-form" action="<?=$editing?Html::e(Url::to('/pages/'.$page['id'].'/edit')):Html::e(Url::to('/spaces/'.$space['space_key'].'/pages/create'))?>">
  <?=Csrf::field()?><?php if($editing):?><input type="hidden" name="base_version" value="<?=Html::e($page['version_no'])?>" id="base_version"><?php endif;?>
  <label>Tytuł<input name="title" id="page-title" value="<?=Html::e($page['title']??'')?>" required maxlength="255"></label>
  <?php if(!$editing && !empty($templatesList)):?><label>Szablon<select name="template_id" id="template-select"><option value="0">Pusta strona</option><?php foreach($templatesList as $tpl):?><option value="<?=Html::e($tpl['id'])?>" data-content="<?=Html::e(base64_encode((string)$tpl['content']))?>" <?=(int)($selectedTemplate??0)===(int)$tpl['id']?'selected':''?>><?=Html::e($tpl['name'])?><?=!empty($tpl['space_name'])?' · '.Html::e($tpl['space_name']):''?></option><?php endforeach;?></select><small>Wybrany szablon wstawia treść, etykiety i właściwości strony.</small></label><?php endif;?>
  <label>Strona nadrzędna<select name="parent_id"><option value="0">— brak —</option><?php foreach($tree as $node):if($editing&&(int)$node['id']===(int)$page['id'])continue;?><option value="<?=Html::e($node['id'])?>" <?=($editing&&(int)($page['parent_id']??0)===(int)$node['id'])?'selected':''?>><?=Html::e($node['title'])?></option><?php endforeach;?></select></label>
  <div class="editor-toolbar" role="toolbar" aria-label="Narzędzia edytora"><button type="button" data-cmd="bold"><b>B</b></button><button type="button" data-cmd="italic"><i>I</i></button><button type="button" data-cmd="underline"><u>U</u></button><button type="button" data-cmd="insertUnorderedList">Lista</button><button type="button" data-cmd="insertOrderedList">Numeracja</button><button type="button" data-block="h2">H2</button><button type="button" data-block="h3">H3</button><button type="button" data-block="blockquote">Cytat</button><button type="button" data-block="pre">Kod</button><button type="button" data-macro="info">Info</button><button type="button" data-macro="warning">Warning</button><button type="button" data-macro="success">Success</button><button type="button" data-macro="error">Error</button><button type="button" data-macro="expand">Expand</button><button type="button" data-macro="mermaid">Mermaid</button><button type="button" data-macro="toc">TOC</button><button type="button" data-macro="children">Children</button><button type="button" data-fullscreen>Pełny ekran</button><span id="autosave-state" class="muted" aria-live="polite"></span></div>
  <div class="editor-wrap"><div id="rich-editor" class="rich-editor" contenteditable="true" data-autosave-url="<?=$editing?Html::e(Url::to('/api/pages/'.$page['id'].'/draft')):''?>" data-user-autocomplete-url="<?=Html::e(Url::to('/api/users/autocomplete'))?>" data-attachment-upload-url="<?=$editing?Html::e(Url::to('/pages/'.$page['id'].'/attachments')):''?>"><?=$page['content']??''?></div><div class="mention-menu" data-mention-menu hidden></div></div>
  <textarea name="content" id="content-field" hidden></textarea>
  <?php if($editing):?><div class="presence-indicator" data-presence data-url="<?=Html::e(Url::to('/api/pages/'.$page['id'].'/presence'))?>" data-csrf="<?=Html::e(Csrf::token())?>" hidden></div><div class="grid"><label>Właściciel<input name="owner_username" value="<?=Html::e($page['owner_username']??'')?>" data-user-input autocomplete="off" placeholder="username"></label><label>Data przeglądu<input type="date" name="review_date" value="<?=Html::e($page['review_date']??'')?>"></label></div><label>Komentarz zmian<input name="change_comment" maxlength="500" placeholder="Co zostało zmienione?"></label><?php endif;?>
  <div class="actions"><button class="button">Zapisz</button><a class="button secondary" href="<?=$editing?Html::e(Url::to('/pages/'.$page['id'])):Html::e(Url::to('/spaces/'.$space['space_key']))?>">Anuluj</a></div>
</form>
