<?php use ImWiki\Security\Csrf;use ImWiki\Security\Html;use ImWiki\Support\Url;$title=$space['name']; ?>
<div class="page-head"><div><p class="eyebrow">Przestrzeń · <?=Html::e($space['space_key'])?></p><h1><?=Html::e($space['name'])?></h1><p><?=Html::e($space['description'])?></p></div><div class="actions"><?php if($canCreate):?><a class="button" href="<?=Html::e(Url::to('/spaces/'.$space['space_key'].'/pages/create'))?>">Utwórz stronę</a><?php endif;?><?php if($canManage):?><a class="button secondary" href="<?=Html::e(Url::to('/spaces/'.$space['space_key'].'/settings'))?>">Ustawienia</a><a class="button secondary" href="<?=Html::e(Url::to('/spaces/'.$space['space_key'].'/webhooks'))?>">Webhooki</a><?php endif;?><form method="post" action="<?=Html::e(Url::to('/spaces/'.$space['space_key'].'/favorite'))?>"><?=Csrf::field()?><button class="button secondary"><?=$isFavorite?'Usuń z ulubionych':'Dodaj do ulubionych'?></button></form><form method="post" action="<?=Html::e(Url::to('/spaces/'.$space['space_key'].'/watch'))?>"><?=Csrf::field()?><button class="button secondary"><?=$isWatching?'Przestań obserwować':'Obserwuj'?></button></form></div></div>
<section class="card section-card"><div class="section-heading"><h2>Drzewo stron</h2><span class="muted"><?php if($canManage):?>Przeciągnij stronę na inną stronę lub na „root”. <?php endif;?>Podstrony są pobierane po rozwinięciu.</span></div>
<?php if(!$children):?><div class="empty-state"><p class="muted">Nie ma jeszcze stron widocznych dla Ciebie w tej przestrzeni.</p><?php if($canCreate):?><a class="button" href="<?=Html::e(Url::to('/spaces/'.$space['space_key'].'/pages/create'))?>">Utwórz pierwszą stronę</a><?php endif;?></div><?php else:?>
<div data-page-tree data-space-id="<?=Html::e($space['id'])?>" data-tree-manage="<?=$canManage?'1':'0'?>" data-tree-move-template="<?=Html::e(Url::to('/api/pages/__ID__/tree-move'))?>" data-tree-children-url="<?=Html::e(Url::to('/api/spaces/'.$space['space_key'].'/tree'))?>" data-page-url-template="<?=Html::e(Url::to('/pages/__ID__'))?>" data-csrf="<?=Html::e(Csrf::token())?>">
  <div class="tree-root-drop" data-root-drop <?=$canManage?'':'hidden'?>>Przenieś do root</div>
  <ul class="page-tree root">
  <?php foreach($children as $node):$id=(int)$node['id'];?>
    <li class="page-tree-item" data-page-id="<?=$id?>" data-parent-id="0" <?=$canManage?'draggable="true"':''?>>
      <div class="page-tree-line"><?php if(!empty($node['has_children'])):?><button type="button" class="tree-expand" data-tree-expand aria-expanded="false" aria-label="Rozwiń podstrony">›</button><?php else:?><span class="tree-expand-spacer"></span><?php endif;?><a href="<?=Html::e(Url::to('/pages/'.$id))?>"><?=Html::e($node['title'])?></a></div>
    </li>
  <?php endforeach;?>
  </ul>
  <?php if(count($children)>=250):?><p class="muted">Wyświetlono pierwsze strony root. Dalsze elementy są dostępne przez wyszukiwarkę; kolejne poziomy drzewa są ładowane na żądanie.</p><?php endif;?>
</div>
<?php endif;?></section>

<section class="card section-card"><div class="section-heading"><div><p class="eyebrow">Przegląd</p><h2>Statystyki Space</h2></div><span class="badge neutral"><?=Html::e($pageCount>=5000?'5000+':(string)$pageCount)?> stron</span></div><div class="dashboard-grid"><div><h3>Popularne strony</h3><?php if(!$popularPages):?><p class="muted">Brak danych odwiedzin.</p><?php endif;?><?php foreach($popularPages as $p):?><a class="list-row" href="<?=Html::e(Url::to('/pages/'.$p['id']))?>"><span><?=Html::e($p['title'])?></span><small><?=Html::e($p['views'])?> wyświetleń</small></a><?php endforeach;?></div><div><h3>Aktywni autorzy</h3><?php foreach($contributors as $c):?><div class="list-row"><span><?=Html::e($c['name']?:$c['username'])?></span><small><?=Html::e($c['edits'])?> wersji</small></div><?php endforeach;?></div><?php if($sidebarLinks):?><div><h3>Skróty</h3><?php foreach($sidebarLinks as $link):$href=$link['type']==='internal'?Url::to($link['url']):$link['url'];?><a class="list-row" href="<?=Html::e($href)?>" <?=$link['type']==='external'?'rel="noopener noreferrer"':''?>><?=Html::e($link['label'])?></a><?php endforeach;?></div><?php endif;?></div></section>

<section class="card section-card"><div class="section-heading"><div><p class="eyebrow">Przenoszenie danych</p><h2>Import / eksport</h2></div><a class="button secondary" href="<?=Html::e(Url::to('/spaces/'.$space['space_key'].'/export.zip'))?>">Eksportuj ZIP</a></div><?php if(isset($_GET['imported'])):?><div class="alert success">Zaimportowano <?=Html::e((string)$_GET['imported'])?> stron.</div><?php elseif(($_GET['import']??'')==='error'):?><div class="alert danger">Import został odrzucony. Sprawdź format, rozmiar i zawartość pliku.</div><?php endif;?><?php if($canCreate):?><form method="post" enctype="multipart/form-data" action="<?=Html::e(Url::to('/spaces/'.$space['space_key'].'/import'))?>" class="grid compact-form"><?=Csrf::field()?><label>Format<select name="type"><option value="md">Markdown</option><option value="zip">ZIP z Markdown</option></select></label><label>Plik<input type="file" name="import_file" accept=".md,.markdown,.zip" required></label><div class="form-action"><button class="button">Importuj</button></div></form><?php endif;?></section>
