<?php use ImWiki\Security\Csrf;use ImWiki\Security\Html;use ImWiki\Support\Url;$title=$space['name']; ?>
<div class="page-head"><div><p class="eyebrow">Przestrzeń · <?=Html::e($space['space_key'])?></p><h1><?=Html::e($space['name'])?></h1><p><?=Html::e($space['description'])?></p></div><div class="actions"><?php if($canCreate):?><a class="button" href="<?=Html::e(Url::to('/spaces/'.$space['space_key'].'/pages/create'))?>">Utwórz stronę</a><?php endif;?><?php if($canManage):?><a class="button secondary" href="<?=Html::e(Url::to('/spaces/'.$space['space_key'].'/settings'))?>">Ustawienia</a><a class="button secondary" href="<?=Html::e(Url::to('/spaces/'.$space['space_key'].'/webhooks'))?>">Webhooki</a><?php endif;?><form method="post" action="<?=Html::e(Url::to('/spaces/'.$space['space_key'].'/favorite'))?>"><?=Csrf::field()?><button class="button secondary"><?=$isFavorite?'Usuń z ulubionych':'Dodaj do ulubionych'?></button></form><form method="post" action="<?=Html::e(Url::to('/spaces/'.$space['space_key'].'/watch'))?>"><?=Csrf::field()?><button class="button secondary"><?=$isWatching?'Przestań obserwować':'Obserwuj'?></button></form></div></div>
<section class="card section-card"><div class="section-heading"><h2>Drzewo stron</h2><?php if($canManage):?><span class="muted">Przeciągnij stronę na inną stronę lub na „root”.</span><?php endif;?></div>
<?php if(!$tree):?><div class="empty-state"><p class="muted">Nie ma jeszcze stron widocznych dla Ciebie w tej przestrzeni.</p><?php if($canCreate):?><a class="button" href="<?=Html::e(Url::to('/spaces/'.$space['space_key'].'/pages/create'))?>">Utwórz pierwszą stronę</a><?php endif;?></div><?php else:?>
<?php $byParent=[];foreach($tree as $item)$byParent[(int)($item['parent_id']??0)][]=$item;$renderTree=function(int $parent=0,int $depth=0)use(&$renderTree,$byParent,$space,$canManage){if($depth>20||empty($byParent[$parent]))return;echo '<ul class="page-tree'.($parent===0?' root':'').'">';foreach($byParent[$parent] as $node){$id=(int)$node['id'];echo '<li class="page-tree-item" data-page-id="'.$id.'" data-parent-id="'.$parent.'" '.($canManage?'draggable="true"':'').'>';echo '<a href="'.Html::e(Url::to('/pages/'.$id)).'">'.Html::e($node['title']).'</a>';if(!empty($byParent[$id]))$renderTree($id,$depth+1);echo '</li>';}echo '</ul>';};?>
<div data-page-tree data-space-id="<?=Html::e($space['id'])?>" data-tree-move-template="<?=Html::e(Url::to('/api/pages/__ID__/tree-move'))?>" data-csrf="<?=Html::e(Csrf::token())?>"><div class="tree-root-drop" data-root-drop <?=$canManage?'':'hidden'?>>Przenieś do root</div><?php $renderTree();?></div>
<?php endif;?></section>

<section class="card section-card"><div class="section-heading"><div><p class="eyebrow">Przegląd</p><h2>Statystyki Space</h2></div><span class="badge neutral"><?=Html::e($pageCount)?> stron</span></div><div class="dashboard-grid"><div><h3>Popularne strony</h3><?php if(!$popularPages):?><p class="muted">Brak danych odwiedzin.</p><?php endif;?><?php foreach($popularPages as $p):?><a class="list-row" href="<?=Html::e(Url::to('/pages/'.$p['id']))?>"><span><?=Html::e($p['title'])?></span><small><?=Html::e($p['views'])?> wyświetleń</small></a><?php endforeach;?></div><div><h3>Aktywni autorzy</h3><?php foreach($contributors as $c):?><div class="list-row"><span><?=Html::e($c['name']?:$c['username'])?></span><small><?=Html::e($c['edits'])?> wersji</small></div><?php endforeach;?></div><?php if($sidebarLinks):?><div><h3>Skróty</h3><?php foreach($sidebarLinks as $link):$href=$link['type']==='internal'?Url::to($link['url']):$link['url'];?><a class="list-row" href="<?=Html::e($href)?>" <?=$link['type']==='external'?'rel="noopener noreferrer"':''?>><?=Html::e($link['label'])?></a><?php endforeach;?></div><?php endif;?></div></section>

<section class="card section-card"><div class="section-heading"><div><p class="eyebrow">Przenoszenie danych</p><h2>Import / eksport</h2></div><a class="button secondary" href="<?=Html::e(Url::to('/spaces/'.$space['space_key'].'/export.zip'))?>">Eksportuj ZIP</a></div><?php if(isset($_GET['imported'])):?><div class="alert success">Zaimportowano <?=Html::e((string)$_GET['imported'])?> stron.</div><?php elseif(($_GET['import']??'')==='error'):?><div class="alert danger">Import został odrzucony. Sprawdź format, rozmiar i zawartość pliku.</div><?php endif;?><?php if($canCreate):?><form method="post" enctype="multipart/form-data" action="<?=Html::e(Url::to('/spaces/'.$space['space_key'].'/import'))?>" class="grid compact-form"><?=Csrf::field()?><label>Format<select name="type"><option value="md">Markdown</option><option value="zip">ZIP z Markdown</option></select></label><label>Plik<input type="file" name="import_file" accept=".md,.markdown,.zip" required></label><div class="form-action"><button class="button">Importuj</button></div></form><?php endif;?></section>
