<?php
use ImWiki\Security\Csrf;
use ImWiki\Security\Html;
use ImWiki\Support\Url;
$title='Authentication';
?>
<div class="page-head"><div><p class="eyebrow">Administracja · Security</p><h1>Authentication</h1><p class="muted">Local pozostaje awaryjną ścieżką logowania. LDAP i OIDC są opcjonalne i nie są wymagane do działania imWiki.</p></div></div>
<?php if($message):?><div class="alert <?=str_contains($message,'error')?'danger':'success'?>"><?=Html::e($message)?></div><?php endif;?>
<div class="grid admin-grid">
<section class="card"><h2>Providery</h2><?php foreach($providers as $provider):?><div class="system-row"><div><strong><?=Html::e($provider['display_name'])?></strong><small><?=Html::e($provider['provider_type'])?> · <?=Html::e($provider['provider_key'])?></small></div><form method="post" action="<?=Html::e(Url::to('/admin/authentication/providers/'.rawurlencode($provider['provider_key']).'/toggle'))?>"><?=Csrf::field()?><input type="hidden" name="enabled" value="<?=$provider['enabled']?'0':'1'?>"><button class="button secondary" <?=$provider['provider_key']==='local'?'disabled':''?>><?=$provider['enabled']?'Wyłącz':'Włącz'?></button></form></div><?php endforeach;?><form method="post" action="<?=Html::e(Url::to('/admin/authentication/oidc-feature'))?>" class="compact-form"><?=Csrf::field()?><label><input type="checkbox" name="enabled" value="1" <?=$oidcEnabled?'checked':''?>> Feature flag OIDC</label><button class="button secondary">Zapisz flagę</button></form></section>
<section class="card"><h2>LDAP</h2><form method="post" action="<?=Html::e(Url::to('/admin/authentication/ldap'))?>"><?=Csrf::field()?><div class="grid"><label>Provider key<input name="provider_key" value="ldap" pattern="[a-z0-9_-]{2,80}" required></label><label>Nazwa<input name="display_name" value="LDAP" required></label><label>Host<input name="host" required placeholder="ldap.example.org"></label><label>Port<input name="port" type="number" min="1" max="65535" value="636"></label><label>Base DN<input name="base_dn" required placeholder="dc=example,dc=org"></label><label>Bind DN<input name="bind_dn"></label><label>Bind Password<input name="bind_password" type="password" autocomplete="new-password"></label><label>User filter<input name="user_filter" value="(uid={username})" required></label><label>TLS<select name="tls_mode"><option value="ldaps">LDAPS</option><option value="starttls">StartTLS</option></select></label><label>Timeout<input name="timeout" type="number" min="2" max="15" value="5"></label><label>Group sync<select name="group_sync_mode"><option value="off">Off</option><option value="map_existing">Map existing</option><option value="create_missing">Create missing</option><option value="sync">Synchronize</option></select></label><label>Default role<input name="default_role" value="user"></label></div><label><input type="checkbox" name="enabled" value="1"> Włącz provider</label><label><input type="checkbox" name="auto_provision" value="1"> Auto provisioning</label><button class="button">Zapisz LDAP</button></form></section>
<section class="card"><h2>OpenID Connect</h2><form method="post" action="<?=Html::e(Url::to('/admin/authentication/oidc'))?>"><?=Csrf::field()?><div class="grid"><label>Provider key<input name="provider_key" value="oidc" pattern="[a-z0-9_-]{2,80}" required></label><label>Nazwa<input name="display_name" value="OpenID Connect" required></label><label>Issuer HTTPS<input name="issuer" type="url" placeholder="https://id.example.org" required></label><label>Client ID<input name="client_id" required></label><label>Client secret<input name="client_secret" type="password" autocomplete="new-password"></label><label>Scopes<input name="scopes" value="openid profile email"></label><label>Username claim<input name="claim_username" value="preferred_username"></label><label>E-mail claim<input name="claim_email" value="email"></label><label>Groups claim<input name="claim_groups" value="groups"></label><label>Group sync<select name="group_sync_mode"><option value="off">Off</option><option value="map_existing">Map existing</option><option value="create_missing">Create missing</option><option value="sync">Synchronize</option></select></label><label>Default role<input name="default_role" value="user"></label></div><label><input type="checkbox" name="enabled" value="1"> Włącz provider</label><label><input type="checkbox" name="auto_provision" value="1"> Auto provisioning</label><button class="button">Zapisz OIDC</button></form><p class="muted">OIDC wymaga HTTPS issuer. Callback używa state, nonce, PKCE S256 oraz weryfikacji podpisu RS256/JWKS.</p></section>
</div>
