<?php use ImWiki\Security\Csrf;use ImWiki\Security\Html;use ImWiki\Support\Url;$title='Backup';$statusLabels=['queued'=>'W kolejce','running'=>'Tworzenie','ready'=>'Gotowy','failed'=>'Błąd','expired'=>'Wygasł'];?>
<div class="page-head"><div><p class="eyebrow">Administracja</p><h1>Backup</h1><p class="muted">Backup jest tworzony przez kolejkę zadań. Archiwum zawiera spójny snapshot SQL, używane uploady, metadane i manifest SHA-256 bez haseł aplikacji.</p></div><a class="button secondary" href="<?=Html::e(Url::to('/admin/backup'))?>">Odśwież status</a></div>
<?php if($queuedId):?><div class="alert success">Backup #<?=Html::e($queuedId)?> został dodany do kolejki. Worker utworzy archiwum poza requestem WWW.</div><?php endif;?>
<?php if(($_GET['error']??'')==='queue'):?><div class="alert danger">Nie udało się dodać backupu do kolejki.</div><?php endif;?>
<section class="card section-card">
  <?php if(!$zipAvailable):?><div class="alert warn">PHP ZipArchive nie jest dostępny. Backup ZIP oraz import/export ZIP są wyłączone.</div><?php else:?><form method="post" action="<?=Html::e(Url::to('/admin/backup/create'))?>"><?=Csrf::field()?><button class="button">Utwórz backup w tle</button></form><?php endif;?>
  <h2>Ostatnie backupy</h2>
  <?php if(!$artifacts):?><p class="muted">Nie utworzono jeszcze backupu.</p><?php else:?><div class="table-wrap"><table><thead><tr><th>ID</th><th>Status</th><th>Administrator</th><th>Utworzono</th><th>Rozmiar</th><th>Wygasa</th><th>Akcja</th></tr></thead><tbody><?php foreach($artifacts as $artifact):?><tr><td>#<?=Html::e($artifact['id'])?></td><td><span class="badge neutral"><?=Html::e($statusLabels[$artifact['status']]??$artifact['status'])?></span><?php if($artifact['status']==='failed'&&!empty($artifact['error_message'])):?><small class="danger-text"><?=Html::e($artifact['error_message'])?></small><?php endif;?></td><td><?=Html::e($artifact['username'])?></td><td><?=Html::e($artifact['created_at'])?></td><td><?=!empty($artifact['size_bytes'])?Html::e(number_format((int)$artifact['size_bytes']/1024/1024,2,',',' ').' MB'):'—'?></td><td><?=Html::e($artifact['expires_at']??'—')?></td><td><?php if($artifact['status']==='ready'):?><a class="button small" href="<?=Html::e(Url::to('/admin/backup/'.$artifact['id'].'/download'))?>">Pobierz</a><?php elseif($artifact['status']==='failed'&&(int)$artifact['requested_by']===(int)$currentUser['id']):?><form method="post" class="inline" action="<?=Html::e(Url::to('/admin/backup/'.$artifact['id'].'/retry'))?>"><?=Csrf::field()?><button class="button small secondary">Ponów</button></form><?php else:?>—<?php endif;?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
</section>
<section class="card section-card"><h2>Weryfikacja i restore</h2><p>Restore pozostaje operacją offline. Najpierw zatrzymaj ruch do aplikacji i zweryfikuj archiwum.</p><pre><code>php bin/backup-verify.php /ścieżka/backup.zip
php bin/restore.php /ścieżka/backup.zip
php bin/restore.php /ścieżka/backup.zip --apply --force</code></pre><p class="muted">Pierwsze uruchomienie <code>restore.php</code> wykonuje wyłącznie walidację. Zmiana bazy wymaga jednocześnie <code>--apply --force</code>.</p></section>
