<?php
use ImWiki\Security\Csrf;
use ImWiki\Security\Html;
use ImWiki\Support\Url;
$title='Enterprise Administration';
$bulk=$_SESSION['enterprise_bulk_result']??null;unset($_SESSION['enterprise_bulk_result']);
$verify=$_SESSION['storage_verify_result']??null;unset($_SESSION['storage_verify_result']);
$tabs=['overview'=>'Overview','spaces'=>'Spaces','governance'=>'Governance','schemas'=>'Structured content','features'=>'Feature flags','security'=>'Security policies','jobs'=>'Jobs','storage'=>'Storage','audit'=>'Audit','acl'=>'ACL diagnostics'];
?>
<div class="page-head"><div><p class="eyebrow">Administracja</p><h1>Enterprise Administration</h1><p class="muted">Operacje enterprise są dostępne przez web UI; podstawowe działanie nie wymaga CLI ani usług zewnętrznych.</p></div></div>
<nav class="tabs" aria-label="Enterprise administration"><?php foreach($tabs as $key=>$label):?><a class="<?=$tab===$key?'active':''?>" href="<?=Html::e(Url::to('/admin/enterprise?tab='.$key))?>"><?=Html::e($label)?></a><?php endforeach;?></nav>
<?php if($message):?><div class="alert <?=str_contains($message,'error')?'danger':'success'?>"><?=Html::e($message)?></div><?php endif;?>

<?php if($tab==='overview'):?>
<div class="grid admin-grid"><section class="card"><h2>Readiness</h2><dl class="system-list"><dt>Status</dt><dd><?=$health['ready']?'READY':'NOT READY'?></dd><dt>Database</dt><dd><?=$health['checks']['database']?'OK':'FAIL'?></dd><dt>Migrations</dt><dd><?=$health['checks']['migrations']?'OK':'FAIL'?></dd><dt>Storage</dt><dd><?=$health['checks']['storage']?'OK':'FAIL'?></dd><dt>Schema</dt><dd><?=Html::e($health['schema']['current'])?> → <?=Html::e($health['schema']['target'])?></dd><dt>Request ID</dt><dd><code><?=Html::e((string)$health['request_id'])?></code></dd></dl><p><a class="button secondary" href="<?=Html::e(Url::to('/admin/health'))?>">Health JSON</a></p></section><section class="card"><h2>Metryki lokalne</h2><dl class="system-list"><?php foreach($health['counts'] as $key=>$value):?><dt><?=Html::e(str_replace('_',' ',$key))?></dt><dd><?=Html::e((string)$value)?></dd><?php endforeach;?></dl><p class="muted">Brak zewnętrznej telemetryki i phone-home.</p></section><section class="card"><h2>Upgrade dry-run</h2><dl class="system-list"><dt>Current</dt><dd><?=Html::e($migrationPlan['current_schema_version'])?></dd><dt>Target</dt><dd><?=Html::e($migrationPlan['target_schema_version'])?></dd><dt>Pending</dt><dd><?=Html::e((string)$migrationPlan['pending_count'])?></dd><dt>State</dt><dd><?=Html::e((string)($migrationPlan['state']['status']??'unknown'))?></dd></dl><?php if($migrationPlan['pending_count']):?><a class="button" href="<?=Html::e(Url::to('/upgrade.php'))?>">Uruchom bezpieczny upgrade</a><?php endif;?></section></div>

<?php elseif($tab==='spaces'):?>
<div class="grid admin-grid"><section class="card"><h2>Kategorie Spaces</h2><form method="post" action="<?=Html::e(Url::to('/admin/enterprise/categories'))?>"><?=Csrf::field()?><label>Nazwa kategorii<input name="name" maxlength="150" required></label><button class="button">Dodaj kategorię</button></form><ul><?php foreach($categories as $category):?><li><?=Html::e($category['name'])?> <span class="badge neutral"><?=Html::e((string)$category['space_count'])?></span></li><?php endforeach;?></ul></section><section class="card"><h2>Lifecycle Space</h2><form method="post" action="<?=Html::e(Url::to('/admin/enterprise/spaces/lifecycle'))?>"><?=Csrf::field()?><label>Space<select name="space_id" required><?php foreach($spaceTree as $space):?><option value="<?=Html::e((string)$space['id'])?>"><?=Html::e($space['space_key'].' — '.$space['name'])?></option><?php endforeach;?></select></label><label>Lifecycle<select name="lifecycle"><option value="active">Active</option><option value="read_only">Read-only</option><option value="archived">Archived</option><option value="scheduled_deletion">Scheduled for deletion</option></select></label><label>Review date<input type="date" name="review_date"></label><label>Archive date<input type="datetime-local" name="archive_date"></label><button class="button">Zapisz lifecycle</button></form></section></div>
<section class="card"><h2>Hierarchia Spaces</h2><div class="table-wrap"><table><thead><tr><th>Kategoria</th><th>Space</th><th>Owner</th><th>Lifecycle</th><th>Visibility</th></tr></thead><tbody><?php foreach($spaceTree as $space):?><tr><td><?=Html::e((string)($space['category_name']??'—'))?></td><td><a href="<?=Html::e(Url::to('/spaces/'.$space['space_key']))?>"><?=Html::e($space['space_key'].' — '.$space['name'])?></a></td><td><?=Html::e($space['owner_username'])?></td><td><span class="badge neutral"><?=Html::e($space['lifecycle'])?></span></td><td><?=Html::e($space['visibility'])?></td></tr><?php endforeach;?></tbody></table></div></section>

<?php elseif($tab==='governance'):?>
<div class="grid admin-grid"><section class="card"><h2>Klasyfikacje</h2><form method="post" action="<?=Html::e(Url::to('/admin/enterprise/classifications'))?>"><?=Csrf::field()?><label>Key<input name="key" pattern="[a-z0-9_-]{2,50}" required></label><label>Nazwa<input name="name" maxlength="100" required></label><label>Sort order<input name="sort_order" type="number" value="50"></label><label><input type="checkbox" name="is_public" value="1"> Public</label><label><input type="checkbox" name="enabled" value="1" checked> Enabled</label><button class="button">Dodaj / zapisz</button></form><ul><?php foreach($classifications as $c):?><li><strong><?=Html::e($c['name'])?></strong> <code><?=Html::e($c['classification_key'])?></code></li><?php endforeach;?></ul></section><section class="card"><h2>Labels</h2><?php foreach($labels as $label):?><form method="post" action="<?=Html::e(Url::to('/admin/enterprise/labels/rename'))?>" class="compact-form"><?=Csrf::field()?><input type="hidden" name="id" value="<?=Html::e((string)$label['id'])?>"><input name="name" value="<?=Html::e($label['name'])?>" required><span class="badge neutral"><?=Html::e((string)$label['usage_count'])?></span><button class="button secondary">Zmień</button></form><?php endforeach;?></section><section class="card"><h2>Przenieś ownership</h2><form method="post" action="<?=Html::e(Url::to('/admin/enterprise/ownership'))?>"><?=Csrf::field()?><label>Page IDs<textarea name="page_ids" placeholder="12, 13, 14" required></textarea></label><label>Nowy owner ID<input type="number" name="owner_id" min="1" required></label><button class="button">Przenieś ownership</button></form><?php if($bulk):?><pre><?=Html::e(json_encode($bulk,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE))?></pre><?php endif;?></section></div>
<section class="card"><h2>Ownership problems</h2><div class="table-wrap"><table><thead><tr><th>Typ</th><th>ID</th><th>Nazwa</th><th>Owner</th><th>Status</th></tr></thead><tbody><?php foreach($ownership['pages'] as $row):?><tr><td>Page</td><td><?=Html::e((string)$row['id'])?></td><td><?=Html::e($row['title'])?></td><td><?=Html::e((string)$row['owner_username'])?></td><td><?=Html::e((string)$row['owner_status'])?></td></tr><?php endforeach;?><?php foreach($ownership['spaces'] as $row):?><tr><td>Space</td><td><?=Html::e((string)$row['id'])?></td><td><?=Html::e($row['space_key'].' — '.$row['name'])?></td><td><?=Html::e((string)$row['owner_username'])?></td><td><?=Html::e((string)$row['owner_status'])?></td></tr><?php endforeach;?></tbody></table></div></section>

<?php elseif($tab==='schemas'):?>
<div class="grid admin-grid"><section class="card"><h2>Nowy Property Schema</h2><form method="post" action="<?=Html::e(Url::to('/admin/enterprise/schemas'))?>"><?=Csrf::field()?><label>Nazwa<input name="name" required maxlength="150"></label><label>Space ID <small>puste = global</small><input type="number" name="space_id" min="1"></label><label>Opis<input name="description" maxlength="500"></label><label>Fields JSON<textarea name="fields_json" rows="12" required>[{"key":"hostname","label":"Hostname","type":"text","required":true},{"key":"environment","label":"Environment","type":"select","options":["prod","nonprod","dev"]},{"key":"owner","label":"Owner","type":"user"},{"key":"review_date","label":"Review Date","type":"date"}]</textarea></label><button class="button">Utwórz schema</button></form></section><section class="card"><h2>Schemas</h2><?php foreach($schemas as $schema):?><div class="system-row"><div><strong><?=Html::e($schema['name'])?></strong><small>v<?=Html::e((string)$schema['version_no'])?> · <?=Html::e($schema['space_key']??'global')?></small></div></div><?php endforeach;?></section></div>

<?php elseif($tab==='features'):?>
<section class="card"><h2>Feature flags</h2><div class="table-wrap"><table><thead><tr><th>Flag</th><th>Scope</th><th>Space</th><th>Stan</th><th>Akcja</th></tr></thead><tbody><?php foreach($features as $flag):?><tr><td><code><?=Html::e($flag['flag_key'])?></code></td><td><?=Html::e($flag['scope_type'])?></td><td><?=Html::e((string)($flag['space_key']??'global'))?></td><td><?=$flag['enabled']?'On':'Off'?></td><td><form method="post" action="<?=Html::e(Url::to('/admin/enterprise/features'))?>"><?=Csrf::field()?><input type="hidden" name="key" value="<?=Html::e($flag['flag_key'])?>"><input type="hidden" name="space_id" value="<?=Html::e((string)($flag['space_id']??''))?>"><input type="hidden" name="enabled" value="<?=$flag['enabled']?'0':'1'?>"><button class="button secondary"><?=$flag['enabled']?'Wyłącz':'Włącz'?></button></form></td></tr><?php endforeach;?></tbody></table></div></section>

<?php elseif($tab==='security'):?>
<div class="grid admin-grid"><section class="card"><h2>Security policies</h2><form method="post" action="<?=Html::e(Url::to('/admin/enterprise/security'))?>"><?=Csrf::field()?><label>Session lifetime (s)<input type="number" name="session_lifetime" value="<?=Html::e($securityPolicies['security.session_lifetime']?:'28800')?>"></label><label>Idle timeout (s)<input type="number" name="idle_timeout" value="<?=Html::e($securityPolicies['security.idle_timeout']?:'3600')?>"></label><label>Max login attempts<input type="number" name="max_login_attempts" value="<?=Html::e($securityPolicies['security.max_login_attempts']?:'10')?>"></label><label>Lockout seconds<input type="number" name="lockout_seconds" value="<?=Html::e($securityPolicies['security.lockout_seconds']?:'900')?>"></label><label>Minimum password length<input type="number" name="min_password_length" value="<?=Html::e($securityPolicies['security.min_password_length']?:'12')?>"></label><label>Password reset expiry<input type="number" name="password_reset_expiry" value="<?=Html::e($securityPolicies['security.password_reset_expiry']?:'3600')?>"></label><label>Trusted device days<input type="number" name="trusted_device_days" value="<?=Html::e($securityPolicies['security.trusted_device_days']?:'30')?>"></label><label>Trusted proxy CIDRs<textarea name="trusted_proxies"><?=Html::e(implode("\n",$trustedProxies))?></textarea></label><fieldset><legend>Allowed auth</legend><label><input type="checkbox" name="allowed_auth_methods[]" value="local" checked disabled> Local</label><label><input type="checkbox" name="allowed_auth_methods[]" value="ldap"> LDAP</label><label><input type="checkbox" name="allowed_auth_methods[]" value="oidc"> OIDC</label></fieldset><label><input type="checkbox" name="require_2fa" value="1" <?=$securityPolicies['security.require_2fa']==='1'?'checked':''?>> Require 2FA</label><label><input type="checkbox" name="hsts" value="1" <?=$securityPolicies['security.hsts']==='1'?'checked':''?>> HSTS</label><label><input type="checkbox" name="csp_report_only" value="1" <?=$securityPolicies['security.csp_report_only']==='1'?'checked':''?>> CSP Report-Only</label><label><input type="checkbox" name="read_only" value="1" <?=$securityPolicies['system.read_only']==='1'?'checked':''?>> Global read-only</label><button class="button">Zapisz polityki</button></form></section><section class="card"><h2>IP restrictions</h2><form method="post" action="<?=Html::e(Url::to('/admin/enterprise/ip-rules'))?>"><?=Csrf::field()?><label>Scope<select name="scope"><option value="global">Global</option><option value="admin">Admin</option></select></label><label>Action<select name="action"><option value="deny">Deny</option><option value="allow">Allow</option></select></label><label>CIDR<input name="cidr" placeholder="192.0.2.0/24" required></label><label>Opis<input name="description" maxlength="255"></label><button class="button">Dodaj regułę</button></form></section></div>

<?php elseif($tab==='jobs'):?>
<section class="card"><h2>Background jobs</h2><p><?php foreach($jobsDashboard['counts'] as $status=>$count):?><span class="badge neutral"><?=Html::e($status)?>: <?=Html::e((string)$count)?></span> <?php endforeach;?></p><div class="table-wrap"><table><thead><tr><th>ID</th><th>Type</th><th>Priority</th><th>Status</th><th>Attempts</th><th>Error</th><th>Action</th></tr></thead><tbody><?php foreach($jobsDashboard['jobs'] as $job):?><tr><td><?=Html::e((string)$job['id'])?></td><td><?=Html::e($job['job_type'])?></td><td><?=Html::e($job['priority'])?></td><td><?=Html::e($job['status'])?></td><td><?=Html::e($job['attempts'].'/'.$job['max_attempts'])?></td><td><?=Html::e((string)$job['last_error'])?></td><td><?php if(in_array($job['status'],['failed','dead'],true)):?><form method="post" action="<?=Html::e(Url::to('/admin/enterprise/jobs/'.$job['id'].'/retry'))?>" class="inline"><?=Csrf::field()?><button class="button secondary">Retry</button></form><?php endif;?><?php if(in_array($job['status'],['pending','failed','dead'],true)):?><form method="post" action="<?=Html::e(Url::to('/admin/enterprise/jobs/'.$job['id'].'/discard'))?>" class="inline"><?=Csrf::field()?><button class="button danger">Discard</button></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></section>

<?php elseif($tab==='storage'):?>
<div class="grid admin-grid"><section class="card"><h2>Storage</h2><dl class="system-list"><?php foreach($storage as $key=>$value):?><dt><?=Html::e(str_replace('_',' ',$key))?></dt><dd><?=Html::e($value===null?'n/a':(string)$value)?></dd><?php endforeach;?></dl><form method="post" action="<?=Html::e(Url::to('/admin/enterprise/storage/verify'))?>"><?=Csrf::field()?><button class="button">Verify attachment integrity</button></form><?php if($verify):?><pre><?=Html::e(json_encode($verify,JSON_PRETTY_PRINT))?></pre><?php endif;?></section><section class="card"><h2>Cleanup candidates</h2><h3>Orphan files</h3><?php foreach($cleanupCandidates['orphan_files'] as $file):?><form method="post" action="<?=Html::e(Url::to('/admin/enterprise/storage/orphan'))?>" class="compact-form"><?=Csrf::field()?><input type="hidden" name="name" value="<?=Html::e($file['name'])?>"><code><?=Html::e($file['name'])?></code><span><?=Html::e((string)$file['size'])?> B</span><button class="button danger">Usuń po ponownej weryfikacji DB</button></form><?php endforeach;?></section></div>

<?php elseif($tab==='audit'):?>
<section class="card"><h2>Audit log</h2><form method="get" action="<?=Html::e(Url::to('/admin/enterprise'))?>" class="filter-grid"><input type="hidden" name="tab" value="audit"><label>User ID<input name="audit_user" value="<?=Html::e((string)$auditFilters['user_id'])?>"></label><label>Action<input name="audit_action" value="<?=Html::e((string)$auditFilters['action'])?>"></label><label>Category<input name="audit_category" value="<?=Html::e((string)$auditFilters['category'])?>"></label><label>Severity<input name="audit_severity" value="<?=Html::e((string)$auditFilters['severity'])?>"></label><label>IP<input name="audit_ip" value="<?=Html::e((string)$auditFilters['ip'])?>"></label><label>From<input type="date" name="audit_from" value="<?=Html::e((string)$auditFilters['date_from'])?>"></label><label>To<input type="date" name="audit_to" value="<?=Html::e((string)$auditFilters['date_to'])?>"></label><button class="button">Filtruj</button></form><div class="actions"><a class="button secondary" href="<?=Html::e(Url::to('/admin/enterprise/audit/export?format=csv'))?>">Export CSV</a><a class="button secondary" href="<?=Html::e(Url::to('/admin/enterprise/audit/export?format=json'))?>">Export JSON</a></div><div class="table-wrap"><table><thead><tr><th>ID</th><th>When</th><th>User</th><th>Action</th><th>Category</th><th>Severity</th><th>Resource</th><th>IP</th><th>Request ID</th></tr></thead><tbody><?php foreach($audit['items'] as $row):?><tr><td><?=Html::e((string)$row['id'])?></td><td><?=Html::e($row['created_at'])?></td><td><?=Html::e((string)$row['username'])?></td><td><?=Html::e($row['action'])?></td><td><?=Html::e($row['category'])?></td><td><?=Html::e($row['severity'])?></td><td><?=Html::e($row['resource_type'].'#'.(string)$row['resource_id'])?></td><td><?=Html::e($row['ip_address'])?></td><td><code><?=Html::e((string)$row['request_id'])?></code></td></tr><?php endforeach;?></tbody></table></div></section>

<?php elseif($tab==='acl'):?>
<section class="card"><h2>Dlaczego ten użytkownik ma dostęp?</h2><form method="get" action="<?=Html::e(Url::to('/admin/enterprise'))?>"><input type="hidden" name="tab" value="acl"><div class="grid"><label>User ID<input type="number" name="acl_user" min="1" required></label><label>Page ID<input type="number" name="acl_page" min="1" required></label></div><button class="button">Diagnozuj</button></form><?php if($aclResult):?><h3>Effective permissions</h3><pre><?=Html::e(json_encode($aclResult['effective'],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE))?></pre><h3>Inheritance</h3><?php foreach($aclResult['inheritance'] as $step):?><div class="system-row"><strong><?=Html::e($step['level'])?></strong><span><?=Html::e($step['source'])?></span></div><?php endforeach;?><details><summary>Raw grants / roles</summary><pre><?=Html::e(json_encode(['roles'=>$aclResult['roles'],'groups'=>$aclResult['groups'],'space_grants'=>$aclResult['space_grants'],'page_grants'=>$aclResult['page_grants']],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE))?></pre></details><?php endif;?></section>
<?php endif;?>
