<?php
use ImWiki\Security\Csrf;
use ImWiki\Security\Html;
use ImWiki\Support\Url;
$title='Plugins';
?>
<div class="page-head"><div><p class="eyebrow">Administracja</p><h1>Plugins</h1><p class="muted">Pluginy są domyślnie wyłączone. Safe Mode blokuje kod third-party bez wyłączania core imWiki.</p></div></div>
<?php if($message):?><div class="alert <?=str_contains($message,'error')?'danger':'success'?>"><?=Html::e($message)?></div><?php endif;?>
<div class="grid admin-grid"><section class="card"><h2>Stan platformy</h2><dl class="system-list"><dt>Feature flag</dt><dd><?=$featureEnabled?'Włączony':'Wyłączony'?></dd><dt>Safe Mode</dt><dd><?=$safeMode?'Aktywny':'Nieaktywny'?></dd></dl><form method="post" action="<?=Html::e(Url::to('/admin/plugins/feature'))?>"><?=Csrf::field()?><input type="hidden" name="enabled" value="<?=$featureEnabled?'0':'1'?>"><button class="button secondary"><?=$featureEnabled?'Wyłącz pluginy':'Włącz pluginy'?></button></form><p class="muted">Awaryjny Safe Mode można aktywować plikiem <code>storage/safe-mode.flag</code>.</p></section>
<section class="card"><h2>Zainstaluj ZIP</h2><form method="post" enctype="multipart/form-data" action="<?=Html::e(Url::to('/admin/plugins/install'))?>"><?=Csrf::field()?><label>Plugin ZIP<input type="file" name="plugin_zip" accept=".zip,application/zip" required></label><button class="button" <?=(!$featureEnabled||$safeMode)?'disabled':''?>>Zainstaluj</button></form><p class="muted">Manifest <code>plugin.json</code> jest walidowany. Path traversal, przekroczony limit i niekompatybilna wersja są blokowane.</p></section></div>
<section class="card"><h2>Zainstalowane pluginy</h2><?php if(!$plugins):?><p class="muted">Brak pluginów.</p><?php else:?><div class="table-wrap"><table><thead><tr><th>Nazwa</th><th>Wersja</th><th>Autor</th><th>Wymaga imWiki</th><th>Kompatybilny</th><th>Stan</th><th>Akcje</th></tr></thead><tbody><?php foreach($plugins as $plugin):?><tr><td><strong><?=Html::e($plugin['name'])?></strong><small><?=Html::e($plugin['plugin_id'])?></small></td><td><?=Html::e($plugin['version'])?></td><td><?=Html::e((string)$plugin['author'])?></td><td><?=Html::e($plugin['required_imwiki'])?></td><td><?=$plugin['compatible']?'Tak':'Nie'?></td><td><?=$plugin['enabled']?'Włączony':'Wyłączony'?></td><td><div class="actions"><form method="post" action="<?=Html::e(Url::to('/admin/plugins/'.rawurlencode($plugin['plugin_id']).'/toggle'))?>"><?=Csrf::field()?><input type="hidden" name="enabled" value="<?=$plugin['enabled']?'0':'1'?>"><button class="button secondary" <?=(!$plugin['compatible']||$safeMode||(!$featureEnabled&&!$plugin['enabled']))?'disabled':''?>><?=$plugin['enabled']?'Wyłącz':'Włącz'?></button></form><?php if(!$plugin['is_core']):?><form method="post" action="<?=Html::e(Url::to('/admin/plugins/'.rawurlencode($plugin['plugin_id']).'/uninstall'))?>" onsubmit="return confirm('Odinstalować plugin?')"><?=Csrf::field()?><button class="button danger">Odinstaluj</button></form><?php endif;?></div></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
