<?php use ImWiki\Security\Html;use ImWiki\Support\Url;$title='Dashboard'; ?>
<div class="page-head"><div><p class="eyebrow">Dashboard</p><h1>Witaj, <?=Html::e($currentUser['first_name'])?></h1></div><div class="actions"><a class="button" href="<?=Html::e(Url::to('/spaces'))?>">Utwórz stronę</a><a class="button secondary" href="<?=Html::e(Url::to('/profile/dashboard'))?>">Dostosuj</a></div></div>
<div class="dashboard-grid">
<?php if(in_array('recent',$widgets,true)):?><section class="card"><h2>Ostatnio edytowane</h2><?php if(!$recent):?><p class="muted">Brak dostępnych stron.</p><?php endif;?><?php foreach($recent as $p):?><a class="list-row" href="<?=Html::e(Url::to('/pages/'.$p['id']))?>"><span><?=Html::e($p['title'])?></span><small><?=Html::e($p['space_name'])?></small></a><?php endforeach;?></section><?php endif;?>
<?php if(in_array('my_spaces',$widgets,true)):?><section class="card"><h2>Moje przestrzenie</h2><?php if(!$spaces):?><p class="muted">Brak dostępnych przestrzeni.</p><?php endif;?><?php foreach($spaces as $s):?><a class="list-row" href="<?=Html::e(Url::to('/spaces/'.$s['space_key']))?>"><span><?=Html::e($s['name'])?></span><small><?=Html::e($s['space_key'])?></small></a><?php endforeach;?></section><?php endif;?>
<?php if(in_array('favorites',$widgets,true)):?><section class="card"><h2>Ulubione</h2><?php if(!$favorites):?><p class="muted">Brak ulubionych stron.</p><?php endif;?><?php foreach($favorites as $p):?><a class="list-row" href="<?=Html::e(Url::to('/pages/'.$p['id']))?>"><span><?=Html::e($p['title'])?></span><small><?=Html::e($p['space_name'])?></small></a><?php endforeach;?></section><?php endif;?>
<?php if(in_array('tasks',$widgets,true)):?><section class="card"><h2>Zadania</h2><?php if(!$tasks):?><p class="muted">Brak otwartych zadań.</p><?php endif;?><?php foreach($tasks as $t):?><a class="list-row" href="<?=Html::e(Url::to('/pages/'.$t['page_id']))?>"><span><?=Html::e($t['description'])?></span><small><?=Html::e($t['due_date']??'bez terminu')?></small></a><?php endforeach;?></section><?php endif;?>
<?php if(in_array('watched',$widgets,true)):?><section class="card"><h2>Obserwowane</h2><?php if(!$watched):?><p class="muted">Nic jeszcze nie obserwujesz.</p><?php endif;?><?php foreach($watched as $w):?><a class="list-row" href="<?=Html::e(Url::to($w['url']))?>"><span><?=Html::e($w['label'])?></span><small><?=Html::e($w['type'])?></small></a><?php endforeach;?></section><?php endif;?>
<?php if(in_array('drafts',$widgets,true)):?><section class="card"><h2>Szkice</h2><?php if(!$drafts):?><p class="muted">Brak szkiców.</p><?php endif;?><?php foreach($drafts as $d):?><a class="list-row" href="<?=Html::e(Url::to('/pages/'.$d['page_id'].'/edit?draft='.$d['id']))?>"><span><?=Html::e($d['page_title'])?></span><small><?=Html::e($d['updated_at'])?></small></a><?php endforeach;?></section><?php endif;?>
<?php if(in_array('activity',$widgets,true)):?><section class="card"><h2>Aktywność</h2><?php if(!$activity):?><p class="muted">Brak aktywności.</p><?php endif;?><?php foreach($activity as $a):?><div class="list-row"><span><?=Html::e($a['description'])?></span><small><?=Html::e($a['created_at'])?></small></div><?php endforeach;?></section><?php endif;?>
</div>
