<?php use ImWiki\Security\Csrf;use ImWiki\Security\Html;use ImWiki\Support\Url;$title='Wyszukiwanie'; ?>
<div class="page-head"><div><p class="eyebrow">Wyszukiwanie</p><h1><?= $query!==''?'Wyniki dla „'.Html::e($query).'”':'Wyszukiwanie zaawansowane' ?></h1><p class="muted">Składnia: <code>space:IT</code> <code>author:adam</code> <code>owner:ola</code> <code>label:linux</code> <code>status:draft</code> <code>type:page</code>.</p></div></div>
<div class="search-layout"><section class="card"><form class="search-page-form" method="get" action="<?=Html::e(Url::to('/search'))?>"><label>Zapytanie<input name="q" value="<?=Html::e($query)?>" autofocus placeholder="linux space:IT label:server"></label><button class="button">Szukaj</button></form>
<?php if($query!==''&&isset($_GET['save'])):?><div class="alert danger">Nie udało się zapisać wyszukiwania.</div><?php endif;?>
<?php if($query!==''):?><form class="save-search-form" method="post" action="<?=Html::e(Url::to('/search/save'))?>"><?=Csrf::field()?><input type="hidden" name="query" value="<?=Html::e($query)?>"><label>Zapisz wyszukiwanie jako<input name="name" maxlength="190" required placeholder="Dokumentacja Linux wymagająca review"></label><button class="button secondary">Zapisz</button></form><?php endif;?>
<div class="search-summary"><?php if($query!==''):?><span><?=count($results)?> widocznych wyników</span><?php endif;?><?php if(!empty($parsed['filters'])):?><span class="muted">Filtry: <?=Html::e(implode(', ',array_keys($parsed['filters'])))?></span><?php endif;?></div>
<?php if($query!==''&&!$results):?><div class="empty-state"><h2>Brak wyników</h2><p class="muted">Zmień tekst lub usuń część filtrów.</p></div><?php endif;?>
<?php foreach($results as $r):?><a class="search-result" href="<?=Html::e(Url::to('/pages/'.$r['id']))?>"><div><strong><?=Html::e($r['title'])?></strong><p class="muted"><?=Html::e($r['space_name'])?> · autor @<?=Html::e($r['author_username'])?> · <?=Html::e($r['status'])?></p></div><span class="badge neutral"><?=Html::e((string)$r['score'])?></span></a><?php endforeach;?></section>
<aside class="card"><h2>Zapisane wyszukiwania</h2><?php if(!$savedSearches):?><p class="muted">Brak zapisanych wyszukiwań.</p><?php endif;?><?php foreach($savedSearches as $saved):?><div class="saved-search"><a href="<?=Html::e(Url::to('/search?q='.rawurlencode($saved['query_text'])))?>"><strong><?=Html::e($saved['name'])?></strong><small><?=Html::e($saved['query_text'])?></small></a><form method="post" action="<?=Html::e(Url::to('/saved-searches/'.$saved['id'].'/remove'))?>"><?=Csrf::field()?><button class="link-button danger-text">Usuń</button></form></div><?php endforeach;?></aside></div>
