<?php
declare(strict_types=1);

namespace ImWiki\Macros;

use ImWiki\Repositories\PageRepository;
use ImWiki\Security\Authorization;
use ImWiki\Security\Html;
use ImWiki\Support\Url;
use PDO;

final class CoreMacros
{
    public function __construct(private readonly PDO $pdo,private readonly string $prefix,private readonly PageRepository $pages,private readonly Authorization $authz){}

    public function register(MacroRegistry $r):void
    {
        $r->register('toc','Table of contents',[],null,true,fn(array $p,array $c):string=>'<nav class="macro macro-info generated-toc" data-generated-toc><strong>Spis treści</strong></nav>');
        $r->register('children','Children',['limit'],null,false,fn(array $p,array $c):string=>$this->children((int)$c['page']['id'],(int)$c['page']['space_id'],(int)$c['user_id'],(int)($p['limit']??50)));
        $r->register('ancestors','Ancestors',[],null,true,fn(array $p,array $c):string=>$this->ancestors((int)$c['page']['id'],(int)$c['user_id']));
        $r->register('descendants','Descendants',['limit'],null,false,fn(array $p,array $c):string=>$this->descendants((int)$c['page']['id'],(int)$c['page']['space_id'],(int)$c['user_id'],(int)($p['limit']??100)));
        $r->register('related-pages','Related pages',['limit'],null,false,fn(array $p,array $c):string=>$this->related((int)$c['page']['id'],(int)$c['user_id'],(int)($p['limit']??10)));
        $r->register('content-by-label','Content by label',['label','limit'],null,false,fn(array $p,array $c):string=>$this->byLabel((string)($p['label']??''),(int)$c['user_id'],(int)($p['limit']??20)));
        $r->register('recently-updated','Recently updated',['limit'],null,false,fn(array $p,array $c):string=>$this->recent((int)$c['page']['space_id'],(int)$c['user_id'],(int)($p['limit']??10)));
        $r->register('popular-content','Popular content',['days','limit'],null,false,fn(array $p,array $c):string=>$this->popular((int)$c['page']['space_id'],(int)$c['user_id'],(int)($p['days']??30),(int)($p['limit']??10)));
        $r->register('user-profile','User profile',['username'],null,false,fn(array $p,array $c):string=>$this->userProfile((string)($p['username']??''),(int)$c['user_id']));
        $r->register('space-details','Space details',[],null,true,fn(array $p,array $c):string=>$this->spaceDetails((int)$c['page']['space_id'],(int)$c['user_id']));
        $r->register('task-report','Task report',['status','assignee','limit'],null,false,fn(array $p,array $c):string=>$this->taskReport((int)$c['page']['space_id'],(int)$c['user_id'],$p));
        $r->register('page-properties','Page properties',[],null,true,fn(array $p,array $c):string=>$this->properties((int)$c['page']['id']));
        $r->register('page-property-report','Page property report',['schema','limit'],null,false,fn(array $p,array $c):string=>$this->propertyReport((string)($p['schema']??''),(int)$c['user_id'],(int)($p['limit']??25)));
        $r->register('task-list','Task list',[],null,false,fn(array $p,array $c):string=>$this->pageTasks((int)$c['page']['id']));
        $r->register('page','Page link',['id'],null,true,fn(array $p,array $c):string=>$this->pageLink((int)($p['id']??0),(int)$c['user_id']));
    }

    private function children(int $pageId,int $spaceId,int $uid,int $limit):string{$limit=max(1,min(100,$limit));$items=array_slice($this->pages->childrenVisible($spaceId,$pageId,$uid,$this->authz->isAdmin($uid)),0,$limit);return$this->pageList('Podstrony',$items);}
    private function ancestors(int $pageId,int $uid):string{$items=[];foreach($this->pages->breadcrumbs($pageId) as $row){$page=$this->pages->find((int)$row['id']);if($page&&$this->authz->canViewPage($uid,$page))$items[]=$page;}array_pop($items);return$this->pageList('Nadrzędne',$items);}
    private function descendants(int $pageId,int $spaceId,int $uid,int $limit):string{$limit=max(1,min(500,$limit));$all=$this->pages->treeVisible($spaceId,$uid,$this->authz->isAdmin($uid));$byParent=[];foreach($all as $row)$byParent[(int)($row['parent_id']??0)][]=$row;$queue=[$pageId];$out=[];while($queue&&count($out)<$limit){$parent=array_shift($queue);foreach($byParent[$parent]??[] as $row){$out[]=$row;$queue[]=(int)$row['id'];if(count($out)>=$limit)break;}}return$this->pageList('Podstrony zagnieżdżone',$out);}
    private function related(int $pageId,int $uid,int $limit):string{$limit=max(1,min(30,$limit));$s=$this->pdo->prepare("SELECT DISTINCT CASE WHEN source_page_id=? THEN target_page_id ELSE source_page_id END other_id FROM `{$this->prefix}page_relations` WHERE source_page_id=? OR target_page_id=? LIMIT ".$limit);$s->execute([$pageId,$pageId,$pageId]);$items=[];foreach($s->fetchAll(PDO::FETCH_COLUMN) as $id){$p=$this->pages->find((int)$id);if($p&&$this->authz->canViewPage($uid,$p))$items[]=$p;}return$this->pageList('Powiązane strony',$items);}
    private function byLabel(string $label,int $uid,int $limit):string{$label=mb_strtolower(trim($label));if($label==='')return$this->emptyMacro('Treści wg etykiety','Brak etykiety.');$limit=max(1,min(100,$limit));$s=$this->pdo->prepare("SELECT p.id FROM `{$this->prefix}pages` p JOIN `{$this->prefix}page_labels` pl ON pl.page_id=p.id JOIN `{$this->prefix}labels` l ON l.id=pl.label_id WHERE l.name=? AND p.deleted_at IS NULL AND p.status NOT IN ('archived','expired') ORDER BY p.updated_at DESC LIMIT ".$limit);$s->execute([$label]);$items=[];foreach($s->fetchAll(PDO::FETCH_COLUMN) as $id){$p=$this->pages->find((int)$id);if($p&&$this->authz->canViewPage($uid,$p))$items[]=$p;}return$this->pageList('Etykieta: '.$label,$items);}
    private function recent(int $spaceId,int $uid,int $limit):string{$limit=max(1,min(50,$limit));$tree=$this->pages->treeVisible($spaceId,$uid,$this->authz->isAdmin($uid));$ids=array_slice(array_map(static fn(array $r):int=>(int)$r['id'],$tree),0,500);if(!$ids)return$this->emptyMacro('Ostatnio zmienione','Brak stron.');$ph=implode(',',array_fill(0,count($ids),'?'));$s=$this->pdo->prepare("SELECT id,title,updated_at FROM `{$this->prefix}pages` WHERE id IN ({$ph}) ORDER BY updated_at DESC LIMIT ".$limit);$s->execute($ids);$out='<div class="macro macro-info"><strong>Ostatnio zmienione</strong><ul>';foreach($s->fetchAll() as $p)$out.='<li><a href="'.Html::e(Url::to('/pages/'.$p['id'])).'">'.Html::e($p['title']).'</a> <small>'.Html::e($p['updated_at']).'</small></li>';return$out.'</ul></div>';}
    private function popular(int $spaceId,int $uid,int $days,int $limit):string{$days=max(1,min(3650,$days));$limit=max(1,min(50,$limit));$s=$this->pdo->prepare("SELECT p.id,p.title,COUNT(v.id) views FROM `{$this->prefix}pages` p JOIN `{$this->prefix}page_views` v ON v.page_id=p.id AND v.viewed_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL ? DAY) WHERE p.space_id=? AND p.deleted_at IS NULL GROUP BY p.id,p.title ORDER BY views DESC,p.updated_at DESC LIMIT ".$limit);$s->execute([$days,$spaceId]);$items=[];foreach($s->fetchAll() as $r){$p=$this->pages->find((int)$r['id']);if($p&&$this->authz->canViewPage($uid,$p)){$p['title'].=' ('.(int)$r['views'].')';$items[]=$p;}}return$this->pageList('Popularne treści',$items);}
    private function userProfile(string $username,int $viewer):string{$username=trim($username);if($username==='')return$this->emptyMacro('Profil','Brak użytkownika.');$s=$this->pdo->prepare("SELECT id,username,first_name,last_name,avatar_path,department_id,team_id FROM `{$this->prefix}users` WHERE username=? AND status='active' AND deleted_at IS NULL");$s->execute([$username]);$u=$s->fetch();if(!$u)return$this->emptyMacro('Profil','Użytkownik niedostępny.');$name=trim((string)$u['first_name'].' '.(string)$u['last_name'])?:$u['username'];return'<div class="macro macro-info"><strong>'.Html::e($name).'</strong><p>@'.Html::e($u['username']).'</p></div>';}
    private function spaceDetails(int $spaceId,int $uid):string{if(!$this->authz->canViewSpace($uid,$spaceId))return$this->emptyMacro('Space','Niedostępny.');$s=$this->pdo->prepare("SELECT s.name,s.space_key,s.description,s.lifecycle,u.username owner_username FROM `{$this->prefix}spaces` s JOIN `{$this->prefix}users` u ON u.id=s.owner_id WHERE s.id=?");$s->execute([$spaceId]);$r=$s->fetch();if(!$r)return'';return'<div class="macro macro-info"><strong>'.Html::e($r['name']).' · '.Html::e($r['space_key']).'</strong><p>'.Html::e((string)$r['description']).'</p><small>Owner: '.Html::e($r['owner_username']).' · '.Html::e($r['lifecycle']).'</small></div>';}
    private function taskReport(int $spaceId,int $uid,array $params):string{$status=(string)($params['status']??'open');if(!in_array($status,['open','in_progress','done','cancelled','all'],true))$status='open';$limit=max(1,min(100,(int)($params['limit']??30)));$where=['p.space_id=?','p.deleted_at IS NULL'];$args=[$spaceId];if($status!=='all'){$where[]='t.status=?';$args[]=$status;}if(!empty($params['assignee'])){$where[]='u.username=?';$args[]=(string)$params['assignee'];}$s=$this->pdo->prepare("SELECT t.id,t.description,t.status,t.priority,t.due_date,t.page_id,p.title page_title,u.username assignee FROM `{$this->prefix}tasks` t JOIN `{$this->prefix}pages` p ON p.id=t.page_id LEFT JOIN `{$this->prefix}users` u ON u.id=t.assignee_id WHERE ".implode(' AND ',$where)." ORDER BY t.due_date IS NULL,t.due_date,t.priority DESC LIMIT ".$limit);$s->execute($args);$rows=[];foreach($s->fetchAll() as $r){$p=$this->pages->find((int)$r['page_id']);if($p&&$this->authz->canViewPage($uid,$p))$rows[]=$r;}if(!$rows)return$this->emptyMacro('Raport zadań','Brak zadań.');$out='<div class="macro macro-info"><strong>Raport zadań</strong><ul>';foreach($rows as $r)$out.='<li><a href="'.Html::e(Url::to('/pages/'.$r['page_id'])).'">'.Html::e($r['page_title']).'</a>: '.Html::e($r['description']).' <small>'.Html::e($r['status']).' · '.Html::e($r['priority']).($r['due_date']?' · '.Html::e($r['due_date']):'').'</small></li>';return$out.'</ul></div>';}
    private function properties(int $pageId):string{$q=$this->pdo->prepare("SELECT property_key,label,property_type,value_text,value_number,value_date,value_datetime,value_user_id,value_group_id,value_boolean,value_json FROM `{$this->prefix}page_properties` WHERE page_id=? ORDER BY label LIMIT 100");$q->execute([$pageId]);$rows=$q->fetchAll();if(!$rows)return$this->emptyMacro('Właściwości','Brak właściwości.');$out='<div class="macro macro-info"><strong>Właściwości</strong><dl class="system-list">';foreach($rows as $r){$v=$this->propertyValue($r);$out.='<dt>'.Html::e($r['label']).'</dt><dd>'.Html::e(is_array($v)?implode(', ',$v):(string)$v).'</dd>';}return$out.'</dl></div>';}
    private function propertyReport(string $schema,int $uid,int $limit):string{$schema=trim($schema);if($schema==='')return$this->emptyMacro('Raport właściwości','Brak schematu.');$limit=max(1,min(100,$limit));$s=$this->pdo->prepare("SELECT ps.id FROM `{$this->prefix}property_schemas` ps WHERE (ps.name=? OR ps.id=?) AND ps.enabled=1 ORDER BY ps.version_no DESC LIMIT 1");$s->execute([$schema,ctype_digit($schema)?(int)$schema:0]);$sid=(int)($s->fetchColumn()?:0);if($sid<=0)return$this->emptyMacro('Raport właściwości','Nieznany schemat.');$q=$this->pdo->prepare("SELECT id FROM `{$this->prefix}pages` WHERE property_schema_id=? AND deleted_at IS NULL ORDER BY title LIMIT ".$limit);$q->execute([$sid]);$items=[];foreach($q->fetchAll(PDO::FETCH_COLUMN) as $id){$p=$this->pages->find((int)$id);if($p&&$this->authz->canViewPage($uid,$p))$items[]=$p;}return$this->pageList('Raport: '.$schema,$items);}
    private function pageTasks(int $pageId):string{$q=$this->pdo->prepare("SELECT description,status,priority,due_date FROM `{$this->prefix}tasks` WHERE page_id=? ORDER BY status,due_date IS NULL,due_date,created_at LIMIT 100");$q->execute([$pageId]);$rows=$q->fetchAll();if(!$rows)return$this->emptyMacro('Zadania','Brak zadań.');$out='<div class="macro macro-info"><strong>Zadania</strong><ul>';foreach($rows as $r)$out.='<li>'.($r['status']==='done'?'✓ ':'□ ').Html::e($r['description']).' <small>'.Html::e($r['priority']).($r['due_date']?' · '.Html::e($r['due_date']):'').'</small></li>';return$out.'</ul></div>';}
    private function pageLink(int $id,int $uid):string{$p=$this->pages->find($id);if(!$p||!$this->authz->canViewPage($uid,$p))return'<span class="muted">Niedostępna strona</span>';return'<a href="'.Html::e(Url::to('/pages/'.$p['id'])).'">'.Html::e($p['title']).'</a>';}
    private function pageList(string $title,array $items):string{if(!$items)return$this->emptyMacro($title,'Brak wyników.');$out='<div class="macro macro-info"><strong>'.Html::e($title).'</strong><ul>';foreach($items as $p)$out.='<li><a href="'.Html::e(Url::to('/pages/'.$p['id'])).'">'.Html::e($p['title']).'</a></li>';return$out.'</ul></div>';}
    private function emptyMacro(string $title,string $text):string{return'<div class="macro macro-info"><strong>'.Html::e($title).'</strong><p>'.Html::e($text).'</p></div>';}
    private function propertyValue(array $r):mixed{return match((string)$r['property_type']){'integer','decimal','number'=>$r['value_number'],'date'=>$r['value_date'],'datetime'=>$r['value_datetime'],'boolean'=>(int)$r['value_boolean']===1?'Tak':'Nie','user'=>'Użytkownik #'.(int)$r['value_user_id'],'group'=>'Grupa #'.(int)$r['value_group_id'],'multiselect'=>json_decode((string)($r['value_json']??'[]'),true)?:[],default=>$r['value_text']};}
}
