<?php
declare(strict_types=1);
namespace ImWiki\Controllers;
use ImWiki\Http\Request;use ImWiki\Http\Response;use ImWiki\Repositories\PageRepository;use ImWiki\Repositories\SpaceRepository;use ImWiki\Repositories\UserRepository;use ImWiki\Security\Authorization;use ImWiki\Services\NotificationService;use ImWiki\Services\PageOperationService;use ImWiki\Support\Url;use ImWiki\View\View;use PDO;use Throwable;
final class PageOperationController extends BaseController{
 public function __construct(PDO $pdo,string $prefix,View $view,UserRepository $users,Authorization $authz,?NotificationService $notifications,private readonly PageRepository $pages,private readonly SpaceRepository $spaces,private readonly PageOperationService $ops){parent::__construct($pdo,$prefix,$view,$users,$authz,$notifications);}
 public function dialog(Request $r,array $p):void{$uid=$this->requireAuth();$page=$this->pages->find((int)$p['id']);if(!$page||!$this->authz->canEditPage($uid,$page)){http_response_code(403);return;}$spaces=$this->spaces->allVisible($uid,$this->authz->isAdmin($uid));$spaces=array_values(array_filter($spaces,fn($s)=>$this->authz->canCreatePage($uid,(int)$s['id'])));echo $this->view->render('pages/move_copy.php',$this->common(['page'=>$page,'spaces'=>$spaces]));}
 public function move(Request $r,array $p):void{$uid=$this->requireAuth();$this->csrf($r);try{$this->ops->move((int)$p['id'],(int)$r->input('space_id'),($x=(int)$r->input('parent_id'))>0?$x:null,$uid);$this->audit($r,'page.moved','page',(int)$p['id'],'Przeniesiono stronę');Response::redirect(Url::to('/pages/'.$p['id']));}catch(Throwable){Response::redirect(Url::to('/pages/'.$p['id'].'/move?error=1'));}}
 public function copy(Request $r,array $p):void{$uid=$this->requireAuth();$this->csrf($r);try{$id=$this->ops->copy((int)$p['id'],(int)$r->input('space_id'),($x=(int)$r->input('parent_id'))>0?$x:null,$uid);$this->audit($r,'page.copied','page',$id,'Skopiowano stronę');Response::redirect(Url::to('/pages/'.$id));}catch(Throwable){Response::redirect(Url::to('/pages/'.$p['id'].'/move?error=1'));}}

 public function archive(Request $r,array $p):void{$uid=$this->requireAuth();$this->csrf($r);try{$archive=(string)$r->input('archive','1')==='1';$this->ops->archive((int)$p['id'],$uid,$archive);$this->audit($r,$archive?'page.archived':'page.unarchived','page',(int)$p['id'],$archive?'Zarchiwizowano stronę':'Przywrócono stronę');Response::redirect(Url::to('/pages/'.$p['id']));}catch(Throwable){http_response_code(403);}}
 public function trash(Request $r,array $p):void{$uid=$this->requireAuth();$this->csrf($r);try{$page=$this->pages->find((int)$p['id']);$space=$page['space_key']??'';$this->ops->trash((int)$p['id'],$uid);$this->audit($r,'page.trashed','page',(int)$p['id'],'Przeniesiono do kosza');Response::redirect(Url::to('/spaces/'.$space));}catch(Throwable){http_response_code(403);}}
 public function trashList(Request $r):void{$uid=$this->requireAuth();try{$items=$this->ops->trashList($uid);}catch(Throwable){http_response_code(403);return;}echo $this->view->render('admin/trash.php',$this->common(['items'=>$items]));}
 public function restore(Request $r,array $p):void{$uid=$this->requireAuth();$this->csrf($r);try{$this->ops->restoreTrash((int)$p['id'],$uid);$this->audit($r,'page.trash_restored','page',(int)$p['id'],'Przywrócono z kosza');}catch(Throwable){http_response_code(403);return;}Response::redirect(Url::to('/admin/trash'));}
 public function purge(Request $r,array $p):void{$uid=$this->requireAuth();$this->csrf($r);try{$this->ops->purge((int)$p['id'],$uid);$this->audit($r,'page.purged','page',(int)$p['id'],'Usunięto permanentnie');}catch(Throwable){http_response_code(403);return;}Response::redirect(Url::to('/admin/trash'));}

 public function treeMove(Request $r,array $p):void{$uid=$this->requireAuth();$this->csrf($r);header('Content-Type: application/json; charset=utf-8');try{$page=$this->pages->find((int)$p['id']);if(!$page)throw new \RuntimeException('Missing.');$targetSpace=(int)$r->input('space_id',(int)$page['space_id']);$parent=(int)$r->input('parent_id',0);$sort=max(0,min(100000,(int)$r->input('sort_order',0)));$this->ops->move((int)$p['id'],$targetSpace,$parent>0?$parent:null,$uid,$sort);$this->audit($r,'page.tree_moved','page',(int)$p['id'],'Przeniesiono stronę w drzewie');echo json_encode(['ok'=>true]);}catch(\Throwable $e){http_response_code(422);echo json_encode(['ok'=>false,'error'=>'Operacja została odrzucona.']);}}
}
