<?php
declare(strict_types=1);
namespace ImWiki\Controllers;
use ImWiki\Http\Request;use ImWiki\Http\Response;use ImWiki\Repositories\UserRepository;use ImWiki\Security\Authorization;use ImWiki\Services\NotificationService;use ImWiki\Services\SessionService;use ImWiki\Support\Url;use ImWiki\View\View;use PDO;use Throwable;
final class ProfileController extends BaseController{
 public function __construct(PDO $pdo,string $prefix,View $view,UserRepository $users,Authorization $authz,?NotificationService $notifications,private readonly SessionService $sessions){parent::__construct($pdo,$prefix,$view,$users,$authz,$notifications);}
 public function index(Request $r):void{$uid=$this->requireAuth();$u=$this->users->find($uid);echo $this->view->render('profile/index.php',$this->common(['profile'=>$u]));}
 public function update(Request $r):void{$uid=$this->requireAuth();$this->csrf($r);$email=strtolower(trim((string)$r->input('email')));$lang=(string)$r->input('language','pl');$tz=(string)$r->input('timezone','Europe/Warsaw');$theme=(string)$r->input('theme','system');if(!filter_var($email,FILTER_VALIDATE_EMAIL)||!in_array($lang,['pl','en'],true)||!in_array($theme,['light','dark','system'],true)||!in_array($tz,timezone_identifiers_list(),true)){Response::redirect(Url::to('/profile?error=1'));}$s=$this->pdo->prepare("UPDATE `{$this->prefix}users` SET first_name=?,last_name=?,email=?,language=?,timezone=?,theme=?,updated_at=UTC_TIMESTAMP() WHERE id=?");try{$s->execute([trim((string)$r->input('first_name')),trim((string)$r->input('last_name')),$email,$lang,$tz,$theme,$uid]);$this->audit($r,'profile.updated','user',$uid,'Zmieniono profil');Response::redirect(Url::to('/profile?saved=1'));}catch(Throwable){Response::redirect(Url::to('/profile?error=1'));}}
 public function password(Request $r):void{$uid=$this->requireAuth();$this->csrf($r);$u=$this->users->find($uid);$current=(string)$r->input('current_password');$next=(string)$r->input('new_password');$confirm=(string)$r->input('confirm_password');if(!$u||!password_verify($current,(string)$u['password_hash'])||strlen($next)<10||!hash_equals($next,$confirm)){Response::redirect(Url::to('/profile?password=error'));}$hash=password_hash($next,PASSWORD_DEFAULT);$this->pdo->prepare("UPDATE `{$this->prefix}users` SET password_hash=?,force_password_change=0,updated_at=UTC_TIMESTAMP() WHERE id=?")->execute([$hash,$uid]);$this->sessions->revokeOthers($uid);$this->audit($r,'profile.password_changed','user',$uid,'Zmieniono hasło');Response::redirect(Url::to('/profile?password=saved'));}
}
