<?php
declare(strict_types=1);
namespace ImWiki\Controllers;
use ImWiki\Http\Request;use ImWiki\Http\Response;use ImWiki\Repositories\UserRepository;use ImWiki\Security\Authorization;use ImWiki\Services\NotificationService;use ImWiki\Services\UserManagementService;use ImWiki\Support\Url;use ImWiki\View\View;use PDO;use Throwable;
final class UserAdminController extends BaseController{
 public function __construct(PDO $pdo,string $prefix,View $view,UserRepository $users,Authorization $authz,?NotificationService $notifications,private readonly UserManagementService $manage){parent::__construct($pdo,$prefix,$view,$users,$authz,$notifications);}
 private function guard():int{$u=$this->requireAuth();if(!$this->authz->can($u,'users.manage')){http_response_code(403);throw new \RuntimeException('Forbidden.');}return $u;}
 public function users(Request $r):void{try{$this->guard();}catch(Throwable){echo $this->view->render('errors/403.php',$this->common());return;}$q=trim((string)$r->input('q',''));$data=$this->manage->users($q,(int)$r->input('page',1));echo $this->view->render('admin/users.php',$this->common(['usersList'=>$data['items'],'page'=>$data['page'],'pages'=>$data['pages'],'total'=>$data['total'],'query'=>$q]));}
 public function createForm(Request $r):void{$this->guard();echo $this->view->render('admin/user_form.php',$this->common(['edited'=>null,'roles'=>$this->manage->roles(),'error'=>'']));}
 public function create(Request $r):void{$actor=$this->guard();$this->csrf($r);try{$id=$this->manage->create($r->all());$this->audit($r,'user.created','user',$id,'Utworzono użytkownika');Response::redirect(Url::to('/admin/users/'.$id.'/edit'));}catch(Throwable){echo $this->view->render('admin/user_form.php',$this->common(['edited'=>null,'roles'=>$this->manage->roles(),'error'=>'Nie udało się utworzyć użytkownika. Login/e-mail mogą być zajęte.']));}}
 public function editForm(Request $r,array $p):void{$this->guard();$u=$this->manage->user((int)$p['id']);if(!$u){http_response_code(404);return;}echo $this->view->render('admin/user_form.php',$this->common(['edited'=>$u,'roles'=>$this->manage->roles(),'error'=>'']));}
 public function update(Request $r,array $p):void{$this->guard();$this->csrf($r);try{$this->manage->update((int)$p['id'],$r->all());$this->audit($r,'user.updated','user',(int)$p['id'],'Zmieniono użytkownika');Response::redirect(Url::to('/admin/users/'.$p['id'].'/edit?saved=1'));}catch(Throwable){$u=$this->manage->user((int)$p['id']);echo $this->view->render('admin/user_form.php',$this->common(['edited'=>$u,'roles'=>$this->manage->roles(),'error'=>'Nie udało się zapisać użytkownika.']));}}
 public function resetPassword(Request $r,array $p):void{$this->guard();$this->csrf($r);try{$this->manage->resetPassword((int)$p['id'],(string)$r->input('password'));$this->audit($r,'user.password_reset','user',(int)$p['id'],'Administrator zresetował hasło');Response::redirect(Url::to('/admin/users/'.$p['id'].'/edit?password=1'));}catch(Throwable){Response::redirect(Url::to('/admin/users/'.$p['id'].'/edit?error=password'));}}
 public function delete(Request $r,array $p):void{$actor=$this->guard();$this->csrf($r);try{$this->manage->delete((int)$p['id'],$actor);$this->audit($r,'user.deleted','user',(int)$p['id'],'Usunięto użytkownika');Response::redirect(Url::to('/admin/users'));}catch(Throwable){Response::redirect(Url::to('/admin/users/'.$p['id'].'/edit?error=delete'));}}
 public function groups(Request $r):void{$this->guard();echo $this->view->render('admin/groups.php',$this->common(['groups'=>$this->manage->groups()]));}
 public function createGroup(Request $r):void{$this->guard();$this->csrf($r);try{$id=$this->manage->createGroup((string)$r->input('name'),(string)$r->input('label'));$this->audit($r,'group.created','group',$id,'Utworzono grupę');Response::redirect(Url::to('/admin/groups/'.$id));}catch(Throwable){Response::redirect(Url::to('/admin/groups?error=1'));}}
 public function group(Request $r,array $p):void{$this->guard();$g=$this->manage->group((int)$p['id']);if(!$g){http_response_code(404);return;}echo $this->view->render('admin/group_form.php',$this->common(['group'=>$g]));}
 public function updateGroup(Request $r,array $p):void{$this->guard();$this->csrf($r);try{$this->manage->updateGroup((int)$p['id'],(string)$r->input('name'),(string)$r->input('label'));$this->audit($r,'group.updated','group',(int)$p['id'],'Zmieniono grupę');}catch(Throwable){}Response::redirect(Url::to('/admin/groups/'.$p['id']));}
 public function deleteGroup(Request $r,array $p):void{$this->guard();$this->csrf($r);try{$this->manage->deleteGroup((int)$p['id']);$this->audit($r,'group.deleted','group',(int)$p['id'],'Usunięto grupę');Response::redirect(Url::to('/admin/groups'));}catch(Throwable){Response::redirect(Url::to('/admin/groups/'.$p['id'].'?error=delete'));}}
 public function addMember(Request $r,array $p):void{$this->guard();$this->csrf($r);try{$this->manage->addGroupMember((int)$p['id'],(string)$r->input('username'));}catch(Throwable){}Response::redirect(Url::to('/admin/groups/'.$p['id']));}
 public function removeMember(Request $r,array $p):void{$this->guard();$this->csrf($r);$this->manage->removeGroupMember((int)$p['id'],(int)$p['userId']);Response::redirect(Url::to('/admin/groups/'.$p['id']));}
}
