<?php
declare(strict_types=1);
namespace ImWiki\Controllers;
use ImWiki\Http\Request;use ImWiki\Http\Response;use ImWiki\Repositories\SpaceRepository;use ImWiki\Repositories\UserRepository;use ImWiki\Security\Authorization;use ImWiki\Services\NotificationService;use ImWiki\Services\WebhookService;use ImWiki\Support\Url;use ImWiki\View\View;use PDO;use Throwable;
final class WebhookController extends BaseController{
 public function __construct(PDO $pdo,string $prefix,View $view,UserRepository $users,Authorization $authz,?NotificationService $notifications,private readonly SpaceRepository $spaces,private readonly WebhookService $webhooks){parent::__construct($pdo,$prefix,$view,$users,$authz,$notifications);}
 public function index(Request $r,array $p):void{$uid=$this->requireAuth();$space=$this->spaces->findByKey((string)$p['key']);if(!$space||!$this->authz->canManageSpace($uid,(int)$space['id'])){http_response_code(403);echo $this->view->render('errors/403.php',$this->common());return;}echo $this->view->render('spaces/webhooks.php',$this->common(['space'=>$space,'webhooks'=>$this->webhooks->list((int)$space['id'],$uid),'events'=>WebhookService::EVENTS,'createdSecret'=>$_SESSION['created_webhook_secret']??null]));unset($_SESSION['created_webhook_secret']);}
 public function create(Request $r,array $p):void{$uid=$this->requireAuth();$this->csrf($r);$space=$this->spaces->findByKey((string)$p['key']);if(!$space){http_response_code(404);return;}try{$created=$this->webhooks->create((int)$space['id'],$uid,(string)$r->input('name'),(string)$r->input('url'),(array)$r->input('events',[]));$_SESSION['created_webhook_secret']=$created['secret'];$this->audit($r,'webhook.created','webhook',$created['id'],'Utworzono webhook');Response::redirect(Url::to('/spaces/'.$space['space_key'].'/webhooks?created=1'));}catch(Throwable){Response::redirect(Url::to('/spaces/'.$space['space_key'].'/webhooks?error=1'));}}
 public function revoke(Request $r,array $p):void{$uid=$this->requireAuth();$this->csrf($r);$space=$this->spaces->findByKey((string)$p['key']);if(!$space){http_response_code(404);return;}try{$this->webhooks->revoke((int)$p['id'],(int)$space['id'],$uid);$this->audit($r,'webhook.revoked','webhook',(int)$p['id'],'Wyłączono webhook');}catch(Throwable){http_response_code(403);return;}Response::redirect(Url::to('/spaces/'.$space['space_key'].'/webhooks'));}
}
