<?php
declare(strict_types=1);
namespace ImWiki\Controllers;
use ImWiki\Http\Request;use ImWiki\Http\Response;use ImWiki\Repositories\UserRepository;use ImWiki\Security\Authorization;use ImWiki\Services\NotificationService;use ImWiki\Services\WorkflowService;use ImWiki\Support\Url;use ImWiki\View\View;use PDO;
final class WorkflowController extends BaseController{
 public function __construct(PDO $pdo,string $prefix,View $view,UserRepository $users,Authorization $authz,NotificationService $notifications,private readonly WorkflowService $workflow){parent::__construct($pdo,$prefix,$view,$users,$authz,$notifications);}
 public function request(Request $r,array $p):void{$uid=$this->requireAuth();$this->csrf($r);try{$this->workflow->requestReview((int)$p['id'],(string)$r->input('reviewer'),$uid);$this->audit($r,'approval.requested','page',(int)$p['id'],'Wysłano stronę do przeglądu','content');Response::redirect(Url::to('/pages/'.$p['id'].'#workflow'));}catch(\Throwable){Response::redirect(Url::to('/pages/'.$p['id'].'?workflow=error#workflow'));}}
 public function decide(Request $r,array $p):void{$uid=$this->requireAuth();$this->csrf($r);try{$decision=(string)$r->input('decision');$this->workflow->decide((int)$p['id'],$decision,(string)$r->input('comment'),$uid);$this->audit($r,'approval.'.$decision,'page',(int)$p['id'],'Zapisano decyzję akceptacji','content');Response::redirect(Url::to('/pages/'.$p['id'].'#workflow'));}catch(\Throwable){http_response_code(403);echo $this->view->render('errors/403.php',$this->common());}}
 public function publish(Request $r,array $p):void{$uid=$this->requireAuth();$this->csrf($r);try{$this->workflow->publish((int)$p['id'],$uid);$this->audit($r,'page.published','page',(int)$p['id'],'Opublikowano zatwierdzoną stronę','content');Response::redirect(Url::to('/pages/'.$p['id'].'#workflow'));}catch(\Throwable){Response::redirect(Url::to('/pages/'.$p['id'].'?workflow=error#workflow'));}}
 public function draft(Request $r,array $p):void{$uid=$this->requireAuth();$this->csrf($r);try{$this->workflow->setDraft((int)$p['id'],$uid);$this->audit($r,'page.draft','page',(int)$p['id'],'Przeniesiono stronę do szkicu','content');Response::redirect(Url::to('/pages/'.$p['id'].'#workflow'));}catch(\Throwable){Response::redirect(Url::to('/pages/'.$p['id'].'?workflow=error#workflow'));}}
 public function setting(Request $r):void{$uid=$this->requireAuth();$this->csrf($r);if(!$this->authz->can($uid,'administration.access')){http_response_code(403);return;}$this->workflow->setEnabled((string)$r->input('enabled')==='1');$this->audit($r,'workflow.setting','system',null,'Zmieniono ustawienie workflow statusów','settings');Response::redirect(Url::to('/admin/system'));}
}
